objects/Case.object
<CustomObject>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_App_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Progress</fullName>
                    <default>true</default>
                    <label>In-Progress</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Revision Needed</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reviewed</fullName>
                    <isActive>false</isActive>
                    <label>Capacity Reviewed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Individual__c</fullName>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter Contact of Record Type Individual.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Application_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Related_Application__c</fullName>
        <label>Related Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Application Details</relationshipLabel>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Waiting_List_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>All AD related to a Program which is waitlisted</description>
        <label>Waiting List Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Application Details(Related to Program)</relationshipLabel>
        <relationshipName>Application_Details_Prog</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Application Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Program_Service__c.object
<CustomObject>
    <label>Program &amp; Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs &amp; Services</pluralLabel>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>Waiver Program</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CC_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Legal Guardian</fullName>
                </value>
                <value>
                    <fullName>Representative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Representatives(Contact)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DT_Landing_Navigation__c.object
<CustomObject>
    <fields>
        <fullName>Case_Manager_URL__c</fullName>
        <label>Case Manager URL</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <label>Component Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Parameters__c</fullName>
        <inlineHelpText>Parameters should be in format
{&quot;Query_String_Param_Name_1&quot;:&quot;Task_Field_API_Name_1&quot;, &quot;Query_String_Param_Name_2&quot;:&quot;Task_Field_API_Name_2&quot;,
...}</inlineHelpText>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Self_Service_URL__c</fullName>
        <label>Self Service URL</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Landing Navigation</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Landing Navigations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DT_Rule_Version__c.object
<CustomObject>
    <fields>
        <fullName>DT_Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Landing Navigation</label>
        <referenceTo>DT_Landing_Navigation__c</referenceTo>
        <relationshipLabel>Rule Versions</relationshipLabel>
        <relationshipName>Rule_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rule Version</label>
    <nameField>
        <displayFormat>RV-{00000}</displayFormat>
        <label>Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DT_Task__c.object
<CustomObject>
    <description>This object will act as a custom task object to store all tasks related to LTSS</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>DT Tasks</relationshipLabel>
        <relationshipName>Task_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>DT Tasks</relationshipLabel>
        <relationshipName>DT_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DT Tasks</relationshipLabel>
        <relationshipName>LTSS_Task_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DT_Rule_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To identify for which Rule version the task has been created</description>
        <label>Rule Version</label>
        <referenceTo>DT_Rule_Version__c</referenceTo>
        <relationshipName>LTSS_Task_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CC_Test_IndividualSummary.cls
/***************************************************************************************************************************************
 * NAME   : CC_Test_IndividualSummary
 * DESCRIPTION  : Individual Summary Controller Test class
 *    
 * @AUTHOR   : Akshay Mohan
 * @DATE   : 27-Nov-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER				DATE				DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Akshay Mohan				27-Nov-2017			Initial version        
 ****************************************************************************************************************************************/
 @isTest
public class CC_Test_IndividualSummary {
	@testSetup//set up contact and application
    public static void setUpData() {
        String sAppId = CC_TestDataFactory.createNewIndividualApp('Test Guy','Male','123456789',Date.newInstance(1999, 10 , 21))[2];
        System.debug('sAppId: ' + sAppId);
        
    }

    private static CC_IndividualSummary_Controller.IndividualSummarryWrapper getWrapper(String sJSON){
    	String sPrefix ='{ "wrapIndivData" : ';
    	sJSON =sJSON.substring(sJSON.indexOf(sPrefix)+sPrefix.length(),sJSON.lastIndexOf('}'));
    	return (CC_IndividualSummary_Controller.IndividualSummarryWrapper) 
    			JSON.deserialize(sJSON, CC_IndividualSummary_Controller.IndividualSummarryWrapper.class);
    }

    @isTest
    public static void loadModal() {
    	List<CC_Application__c> lstApp = [SELECT ID,Name,CC_Individual__r.Name,CC_Individual__c FROM CC_Application__c];
        System.debug('lstApp: ' + lstApp);
        String sAppId = lstApp[0].Id,sContactId = lstApp[0].CC_Individual__c;

        Case objCase = new Case(Status = System.label.CC_Case_Status_Active, ContactId = sContactId,Action_Date__c =System.now());
        insert objCase;

        CC_Application__c objApp = new CC_Application__c(Id= sAppId, CC_Case__c = objCase.Id);
        update objApp;

        DT_TestDataFactory.createRuleVersion(NULL, TRUE);
        DT_Rule_Version__c objRuleVersion = [SELECT ID, Name FROM DT_Rule_Version__c LIMIT 1];
        DT_Landing_Navigation__c objLandNav = new DT_Landing_Navigation__c(DT_Parameters__c = 'sAppId:Application__c;sContactId:Contact__c;sModule:Application_Intake',
                                                                            Case_Manager_URL__c = 'application', Component_Name__c ='c:CC_ApplicationContainer', Self_Service_URL__c ='application');
        insert objLandNav;
        objRuleVersion.DT_Navigation__c = objLandNav.Id;
        update objRuleVersion;
        DT_Task__c objTask = new DT_Task__c(DT_Rule_Version__c = objRuleVersion.Id, Contact__c = sContactId, Application__c = sAppId, Case__c = objCase.Id);
        insert objTask;

        Test.startTest();
        String sResultJSON = CC_IndividualSummary_Controller.loadData(null,objTask.Id, false);
        Test.stopTest();

        System.debug('sResultJSON: ' + sResultJSON);
        CC_IndividualSummary_Controller.IndividualSummarryWrapper wrapIndivData = getWrapper(sResultJSON);
        System.debug('wrapIndivData: ' + wrapIndivData);
        System.assert(wrapIndivData.lstPrograms==null,'Programs initialized without querying!');
        System.assertEquals('Test Guy'.toUpperCase(),wrapIndivData.sIndivName,'Wrong individual returned!');
        System.assertEquals(CC_Constants.CC_NO_DATA,wrapIndivData.sLGName,'Wrong LG returned!');
        System.assertEquals(CC_Constants.CC_NO_DATA,wrapIndivData.sARName,'Wrong AR returned!');
    }

    @isTest
    public static void loadModalWithRep() {
    	List<CC_Application__c> lstApp = [SELECT ID,Name,CC_Individual__r.Name,CC_Individual__c,CC_Individual__r.AccountId FROM CC_Application__c];

        System.debug('lstApp: ' + lstApp);
        String sAppId = lstApp[0].Id,sContactId = lstApp[0].CC_Individual__c,sAccountId = lstApp[0].CC_Individual__r.AccountId;

        String sRepRTId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Individual);
        
        List<Contact> lstContacts = new List<Contact>();
        Contact objLG = new Contact(CC_Contact_Type__c = System.Label.CC_Contact_Type_Legal_Guardian, AccountId = sAccountId
        							,LastName = 'LG',Parent_Application__c = sAppId, RecordTypeId = sRepRTId);
        Contact objAR = new Contact(CC_Contact_Type__c = System.Label.CC_Contact_Type_Representative, AccountId = sAccountId
        							,LastName = 'AR', Parent_Application__c = sAppId, RecordTypeId = sRepRTId);
        lstContacts.add(objLG);
        lstContacts.add(objAR);
        insert lstContacts;
		System.debug('lstContacts: ' + lstContacts);
		/*Integer start = System.Now().millisecond();
		while(System.Now().millisecond()< start+900){  delay not working
		}*/
		CC_Application__c objApp = new CC_Application__c();
        objApp.CC_Individual__c = sContactId;
        objApp.CC_App_Status__c = System.label.CC_AppStatus_InProgress;
        insert objApp;
        
        System.debug('Testing start for loadModalWithRep');
        Test.startTest();
        objLG = new Contact(CC_Contact_Type__c = System.Label.CC_Contact_Type_Legal_Guardian+';'+System.Label.CC_Contact_Type_Representative,
        							 AccountId = sAccountId, LastName = 'LGAR',Parent_Application__c = objApp.Id, RecordTypeId = sRepRTId);
        insert objLG;
        String sResultJSON = CC_IndividualSummary_Controller.loadData(sContactId,null, false);
        Test.stopTest();

        System.debug('sResultJSON: ' + sResultJSON);
        CC_IndividualSummary_Controller.IndividualSummarryWrapper wrapIndivData = getWrapper(sResultJSON);
        System.debug('wrapIndivData in loadModalWithRep: ' + wrapIndivData);
        System.assert(wrapIndivData.lstPrograms==null,'Programs initialized without querying!');
        System.assertEquals('Test Guy'.toUpperCase(),wrapIndivData.sIndivName,'Wrong individual returned!');
        /*System.assertEquals('LGAR',wrapIndivData.sLGName,'Wrong LG returned!'); //doesnt work since contact is created in same milisecond
        System.assertEquals('LGAR',wrapIndivData.sARName,'Wrong AR returned!');*/
    }

    @isTest
    public static void loadPage() {
    	List<CC_Application__c> lstApp = [SELECT ID,Name,CC_Individual__r.Name,CC_Individual__c FROM CC_Application__c];
        System.debug('lstApp: ' + lstApp);
        String sAppId = lstApp[0].Id,sContactId = lstApp[0].CC_Individual__c;
        Case objCase = new Case(ContactId = sContactId);
        insert objCase;
        CC_Application__c objApp = new CC_Application__c(Id = sAppId, CC_Case__c = objCase.Id);
        update objApp;

        String sRepRTId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Representative);
        List<Contact> lstContacts = new List<Contact>();
        lstContacts.add(new Contact(CC_Contact_Type__c = System.Label.CC_Contact_Type_Legal_Guardian
        							,LastName = 'LG',Parent_Application__c = sAppId, RecordTypeId = sRepRTId));
        lstContacts.add(new Contact(CC_Contact_Type__c = System.Label.CC_Contact_Type_Representative
        							,LastName = 'AR', Parent_Application__c = sAppId, RecordTypeId = sRepRTId));
        insert lstContacts;
        System.debug('lstContacts: ' + lstContacts);

        Test.startTest();
        String sResultJSON = CC_IndividualSummary_Controller.loadData(sContactId,null, true);
        Test.stopTest();

        System.debug('sResultJSON: ' + sResultJSON);
        CC_IndividualSummary_Controller.IndividualSummarryWrapper wrapIndivData = getWrapper(sResultJSON);
        System.debug('wrapIndivData: ' + wrapIndivData);
        System.assert(wrapIndivData.lstPrograms!=null,'Programs not initialized after querying!');
        System.assertEquals('Test Guy'.toUpperCase(),wrapIndivData.sIndivName,'Wrong individual returned!');
        
    }

    @isTest
    public static void loadPageWithMultiplePrograms() {
    	List<CC_Application__c> lstApp = [SELECT ID,Name,CC_Individual__r.Name,CC_Individual__c FROM CC_Application__c];
        System.debug('lstApp: ' + lstApp);
        String sAppId = lstApp[0].Id,sContactId = lstApp[0].CC_Individual__c;
        Case objCase = new Case(ContactId = sContactId);
        insert objCase;
        
        CC_Application__c objApp = new CC_Application__c(Id = sAppId, CC_Case__c = objCase.Id);
        update objApp;

        CC_Program_Service__c objProgram = new CC_Program_Service__c(Name='Test Program',
        													RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_PROGRAM_SERVICE_OBJ, 'Program'));
        insert objProgram;
        System.debug('objProgram: ' + objProgram);

        CC_Application_Detail__c objSelectedApp1= new CC_Application_Detail__c(Waiting_List_Program__c =objProgram.Id, 
        																		Related_Application__c = sAppId,
        																		RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ, CC_Constants.CC_RECORD_TYPE_WAIVER_PROGRAMS)); 
        insert objSelectedApp1;
        System.debug('objSelectedApp1: ' + objSelectedApp1);

        Test.startTest();
        String sResultJSON = CC_IndividualSummary_Controller.loadData(sContactId,null, true);
        Test.stopTest();

        System.debug('sResultJSON: ' + sResultJSON);
        CC_IndividualSummary_Controller.IndividualSummarryWrapper wrapIndivData = getWrapper(sResultJSON);
        System.debug('wrapIndivData: ' + wrapIndivData);
        System.assertEquals(1,wrapIndivData.lstPrograms.size(),'Programs not found after querying!');
        System.assertEquals('Test Program',wrapIndivData.lstPrograms[0].sProgramName,'Wrong program returned!');
    }
}