objects/DT_Rule__c.object
<CustomObject>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether the rule is Active based on the versions</description>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Rule_Type__c</fullName>
        <label>Rule Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                    <default>true</default>
                    <label>Task</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Target_SObject_API_Name__c</fullName>
        <description>API Name of the SObject which the rule is related to</description>
        <label>Target Object</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Task_Name__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DT_Test_RuleExtension.cls
/***************************************************************************************************************************************
 * NAME   : DT_Test_RuleExtension
 * DESCRIPTION  : Test Class for DT_RuleExtension.
 *    
 * @AUTHOR   : Nidhin V K
 * @DATE   : 10-31-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K               10-31-2017          Initial version        
 *
 ****************************************************************************************************************************************/

@isTest
private class DT_Test_RuleExtension {
    
    @testSetup static void setupData() {
        DT_TestDataFactory.createRule(TRUE);
    }
    
    @isTest static void testRuleMethods() {
        
        Test.startTest();
        PageReference pageRef = Page.DT_CreateRules;
        DT_Rule__c objRule = [SELECT 
                                Id, Name, DT_Task_Name__c, DT_Target_SObject_API_Name__c,
                                DT_Rule_Type__c, DT_Priority__c, DT_IsActive__c
                            FROM 
                                DT_Rule__c 
                            LIMIT 1];
        System.debug('objRule>>' + objRule);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController objStdCntrl = new ApexPages.standardController(objRule);
        
        DT_RuleExtension objExtension = new DT_RuleExtension(objStdCntrl);
        System.assert(objExtension.lstTargetObjects.size() > 0);
        
        PageReference pageRef1 = objExtension.cancel();
        System.assertEquals('/' + objRule.Id, pageRef1.getUrl());
        
        objExtension.toggleActivate();
        //System.assertEquals(objRule.DT_IsActive__c, true);
        objRule.DT_IsActive__c = true;
        objExtension.toggleActivate();
        
        PageReference pageRef2 = objExtension.deleteRule();
        System.assertEquals('/apex/DT_ViewRuleList', pageRef2.getUrl());
        objRule.Id = NULL;
        objExtension.toggleActivate();
        objExtension.deleteRule();  
        Test.stopTest();
    }
}