objects/DT_Rule__c.object
<CustomObject>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether the rule is Active based on the versions</description>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Rule_Type__c</fullName>
        <label>Rule Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                    <default>true</default>
                    <label>Task</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Target_SObject_API_Name__c</fullName>
        <description>API Name of the SObject which the rule is related to</description>
        <label>Target Object</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Task_Name__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DT_Rule_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>DT_Rule_Version__c</fullName>
        <label>Rule Version</label>
        <referenceTo>DT_Rule_Version__c</referenceTo>
        <relationshipName>DT_Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DT_Serial_Number__c</fullName>
        <label>Serial Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT_Source_SObject_Field__c</fullName>
        <description>API Name of the sObject field to be considered for comparison or source sobject field to be copied to task object field</description>
        <label>Source SObject Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Target_Task_Field__c</fullName>
        <label>Target Task Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Rule Criterion</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Rule Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DT_Rule_Version__c.object
<CustomObject>
    <fields>
        <fullName>DT_Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Deactivated_Date__c</fullName>
        <label>Deactivated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Queue_Name__c</fullName>
        <description>Contains the Developer Name field value of the Queue assigned</description>
        <label>Queue Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>DT_Rule__c</referenceTo>
        <relationshipName>DT_Rule_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Version</label>
    <nameField>
        <displayFormat>RV-{00000}</displayFormat>
        <label>Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DT_Test_RuleCriteriaExtension.cls
/***************************************************************************************************************************************
 * NAME   : DT_Test_RuleCriteriaExtension
 * DESCRIPTION  : Test Class for DT_RuleCriteriaExtension.
 *    
 * @AUTHOR   : Nidhin V K
 * @DATE   : 11-06-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K               11-06-2017          Initial version        
 *
 ****************************************************************************************************************************************/

@isTest
private class DT_Test_RuleCriteriaExtension {
    
    @testSetup static void setupData() {
        DT_TestDataFactory.createRuleCriteria(NULL, NULL, TRUE);
    }
    
    @isTest static void testRuleCriteriaMethods() {
        Test.startTest();
        PageReference pageRef = Page.DT_CreateRuleCriteria;
        DT_Rule__c objRule = [SELECT 
                                Id, Name, DT_Task_Name__c, DT_Target_SObject_API_Name__c,
                                DT_Rule_Type__c, DT_Priority__c, DT_IsActive__c
                            FROM 
                                DT_Rule__c 
                            LIMIT 1];
        System.debug('objRule>>' + objRule);
        objRule.DT_IsActive__c = TRUE;
        update objRule;
        DT_Rule_Version__c objVersion = [SELECT 
                                            Id, Name, DT_Rule__c, DT_Assignment_Type__c,
                                            DT_Queue_Name__c, DT_IsActive__c, DT_Deactivated_Date__c
                                        FROM 
                                            DT_Rule_Version__c 
                                        LIMIT 1];
        System.debug('objVersion>>' + objVersion);
        DT_Rule_Criterion__c objCriterion = [SELECT 
                                            Id, Name, RecordTypeId, DT_Rule_Version__c,
                                            DT_Serial_Number__c
                                        FROM 
                                            DT_Rule_Criterion__c 
                                        LIMIT 1];
        System.debug('objCriterion>>' + objCriterion);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController objStdCntrl = new ApexPages.standardController(objCriterion);
        
        DT_RuleCriteriaExtension objExtension = new DT_RuleCriteriaExtension(objStdCntrl);
        System.assert(objExtension.lstTaskFields.size() > 0);
        objExtension.populateSObjectFields('InvalidObject');
        
        objExtension.save();
        
        objExtension.selectedRTName = DT_Constants.DT_RECORD_TYPE_COMPARE;
        objCriterion.DT_Source_SObject_Field__c = 'Name';
        objExtension.save();
        
        objCriterion.DT_Source_SObject_Field__c = 'abc';
        objExtension.save();
        
        objExtension.selectedRTName = DT_Constants.DT_RECORD_TYPE_MAP_STATIC;
        objCriterion.DT_Target_Task_Field__c = DT_Constants.DT_FIELD_DUE_DATE;
        objExtension.enableDisableTaskField();
        System.assertEquals(objExtension.bShowTask, TRUE);
        objExtension.save();
        
        objExtension.selectedRTName = DT_Constants.DT_RECORD_TYPE_MAP_SOBJECT;
        objExtension.enableDisableTaskField();
        System.assertEquals(objExtension.bShowTask, TRUE);
        objCriterion.DT_Source_SObject_Field__c = 'Name';
        objExtension.save();
        
        objExtension.deleteCriteria();
        
        objRule.DT_IsActive__c = FALSE;
        objVersion.DT_IsActive__c = TRUE;
        update objRule;
        update objVersion;
        objExtension.deleteCriteria();
        
        Test.stopTest();
    }
}