objects/DT_Rule__c.object
<CustomObject>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether the rule is Active based on the versions</description>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Rule_Type__c</fullName>
        <label>Rule Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                    <default>true</default>
                    <label>Task</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Target_SObject_API_Name__c</fullName>
        <description>API Name of the SObject which the rule is related to</description>
        <label>Target Object</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Task_Name__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DT_Rule_Version__c.object
<CustomObject>
    <fields>
        <fullName>DT_Assignee__c</fullName>
        <label>Assignee</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assign it back to the Submitted Person</fullName>
                </value>
                <value>
                    <fullName>Assign it to latest Task Owner</fullName>
                </value>
                <value>
                    <fullName>Assign it to latest Module Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                    <isActive>false</isActive>
                    <label>Case Manager</label>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                    <isActive>false</isActive>
                    <label>Supervisor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Criteria_Logic__c</fullName>
        <label>Criteria Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Deactivated_Date__c</fullName>
        <label>Deactivated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Queue_Name__c</fullName>
        <description>Contains the Developer Name field value of the Queue assigned</description>
        <label>Queue Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>DT_Rule__c</referenceTo>
        <relationshipName>DT_Rule_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Version</label>
    <nameField>
        <displayFormat>RV-{00000}</displayFormat>
        <label>Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DT_Test_RuleVersionExtension.cls
/***************************************************************************************************************************************
 * NAME   : DT_Test_RuleVersionExtension
 * DESCRIPTION  : Test Class for DT_RuleVersionExtension.
 *    
 * @AUTHOR   : Nidhin V K
 * @DATE   : 11-06-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K               11-06-2017          Initial version        
 *
 ****************************************************************************************************************************************/

@isTest
private class DT_Test_RuleVersionExtension {
    
    @testSetup static void setupData() {
        DT_TestDataFactory.createRuleVersion(NULL, TRUE);
    }
    
    @isTest static void testRuleVersionMethods() {
        Test.startTest();
        PageReference pageRef = Page.DT_CreateRuleVersion;
        DT_Rule__c objRule = [SELECT 
                                Id, Name, DT_Task_Name__c, DT_Target_SObject_API_Name__c,
                                DT_Rule_Type__c, DT_Priority__c, DT_IsActive__c
                            FROM 
                                DT_Rule__c 
                            LIMIT 1];
        System.debug('objRule>>' + objRule);
        objRule.DT_IsActive__c = TRUE;
        update objRule;
        DT_Rule_Version__c objVersion = [SELECT 
                                            Id, Name, DT_Rule__c, DT_Assignment_Type__c,
                                            DT_Queue_Name__c, DT_IsActive__c, DT_Deactivated_Date__c
                                        FROM 
                                            DT_Rule_Version__c 
                                        LIMIT 1];
        System.debug('objVersion>>' + objVersion);
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController objStdCntrl = new ApexPages.standardController(objVersion);
        
        DT_RuleVersionExtension objExtension = new DT_RuleVersionExtension(objStdCntrl);
        System.assert(objExtension.lstQueues.size() > 0);
        
        objExtension.onChangeAssignmentType();
        System.assertEquals(objExtension.bShowAssigneeType, false);
        
        objExtension.toggleActivate();
        
        DT_TestDataFactory.createRuleCriteria(objRule.Id, objVersion.Id, TRUE);
        objExtension.toggleActivate();
        
        objVersion.DT_IsActive__c = false;
        objVersion.DT_Criteria_Logic__c = '(1 AND 2)';
        objRule.DT_IsActive__c = false;
        update objRule;
        update objVersion;
        objExtension.bError = false;
        objExtension.toggleActivate();
        
        objVersion.DT_Assignment_Type__c = System.Label.DT_RULE_VER_TYPE_MANUAL;
        new DT_RuleVersionExtension(objStdCntrl);
        objExtension.onChangeAssignmentType();
        objVersion.DT_Assignee__c = DT_Constants.DT_ASSIGNEE_TYPE_TASK;
        objExtension.onChangeAssigneeType();
        System.assertEquals(objExtension.bShowAssigneeType, true);
        objExtension.populateAssignees(DT_Constants.DT_FIELD_TASK_NAME);
        
        DT_RuleVersionTriggerHandler.checkValidations(new List<DT_Rule_Version__c>{objVersion}, NULL);
        
        objExtension.cloneVersion();
        //System.assertEquals([SELECT Id FROM DT_Rule_Version__c].size(), 2);
        
        objExtension.deleteVersion();
        //System.assertEquals([SELECT Id FROM DT_Rule_Version__c].size(), 1);
        objVersion.Id= NULL;
        objExtension.toggleActivate();
        objExtension.cloneVersion();
        objExtension.deleteVersion();
        Test.stopTest();
    }
}