objects/DT_Rule__c.object
<CustomObject>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether the rule is Active based on the versions</description>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Rule_Type__c</fullName>
        <label>Rule Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                    <default>true</default>
                    <label>Task</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Target_SObject_API_Name__c</fullName>
        <description>API Name of the SObject which the rule is related to</description>
        <label>Target Object</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DT_Rule_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>DT_Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equals To</fullName>
                    <default>true</default>
                    <label>Equals To</label>
                </value>
                <value>
                    <fullName>Not Equals To</fullName>
                </value>
                <value>
                    <fullName>Greater Than</fullName>
                </value>
                <value>
                    <fullName>Greater Than Or Equals To</fullName>
                </value>
                <value>
                    <fullName>Less Than</fullName>
                </value>
                <value>
                    <fullName>Less Than Or Equals To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Rule_Version__c</fullName>
        <label>Rule Version</label>
        <referenceTo>DT_Rule_Version__c</referenceTo>
        <relationshipName>DT_Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DT_Serial_Number__c</fullName>
        <label>Serial Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT_Source_SObject_Field_Type__c</fullName>
        <label>Source SObject Field Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Source_SObject_Field__c</fullName>
        <description>API Name of the sObject field to be considered for comparison or source sobject field to be copied to task object field</description>
        <label>Source SObject Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Target_Task_Field__c</fullName>
        <label>Target Task Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Value_To_Compare__c</fullName>
        <description>Value to compare with source sObject field</description>
        <inlineHelpText>Can have different formats
Date Format: YYYY-MM-DD</inlineHelpText>
        <label>Value To Compare</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Value_to_Map__c</fullName>
        <inlineHelpText>Can have different formats
Date Format: YYYY-MM-DD</inlineHelpText>
        <label>Value to Map</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rule Criterion</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Rule Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DT_Rule_Version__c.object
<CustomObject>
    <fields>
        <fullName>DT_Deactivated_Date__c</fullName>
        <label>Deactivated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>DT_Rule__c</referenceTo>
        <relationshipName>DT_Rule_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Version</label>
    <nameField>
        <displayFormat>RV-{00000}</displayFormat>
        <label>Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DT_RuleCriteriaExtension.cls
/* Class Name   : DT_RuleCriteriaExtension
 * Description  :    
 * Created By   : Nidhin V K
 * Created On   : 07-26-2016

 * Modification Log:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date        Modification ID      Description 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K            07-26-2016        1000            Initial ruleVersion
 * Debalina Chatterjee   09-29-2016        1001            RecordType population  
 *
 */
public with sharing class DT_RuleCriteriaExtension {
    
    public List<SelectOption> lstTaskFields{get; set;}
    
    public List<SelectOption> lstTargetObjectFields{get; set;}
    
    public List<SelectOption> lstOperators{get; set;}

    public Id selectedVal{get;set;}
    
    public Boolean bShowTask{get; set;}
    
    public Boolean bShowError{get; set;}

    public Boolean bShowValueCompare{get; set;}

    public Boolean bTaskType{get; set;}

    public Boolean bShowMapValue{get;set;}

    public Boolean bShowSourceField{get;set;}

    public Boolean bShowDueDate{get;set;}
    
    public DT_Rule_Criterion__c objRuleCriteria;

    public String sDaysToAdd{get;set;}
    
    DT_Rule_Version__c ruleVersion;
    
    public String selectedRTName;
    
    
    /* DT_RuleCriteriaExtension constructor does the basic functionalities like 
     * initialization of objects and get some needed data
     * Enable/Disable Buttons
     * Show/Hide fields
     * @params : controller
     */
    public DT_RuleCriteriaExtension(ApexPages.StandardController controller) {
        
        
        //Get the fileds which are not used in the Page
        if(!Test.isRunningTest())
            controller.addFields(new List<String>{DT_Constants.DT_FIELD_RULE_VERSION, DT_Constants.DT_FIELD_SL_NO});
        this.objRuleCriteria = (DT_Rule_Criterion__c)controller.getRecord();
        System.debug(objRuleCriteria);

        if(String.isNotBlank(ApexPages.currentPage().getParameters().get('RecordType')) &&
            ApexPages.currentPage().getParameters().get('RecordType') != null){
            selectedVal = ApexPages.currentPage().getParameters().get('RecordType');
        }
        else{
            selectedVal = objRuleCriteria.RecordTypeId;
        }    

        System.debug('selectedVal' +selectedVal);

        lstTargetObjectFields = new List<SelectOption>();
        
        //Get the selected Rule details
        ruleVersion = [SELECT
                            Id,
                            DT_IsActive__c,
                            DT_Deactivated_Date__c,
                            DT_Rule__r.DT_Target_SObject_API_Name__c,
                            DT_Rule__r.DT_Rule_Type__c,
                            DT_Rule__r.DT_IsActive__c,
                            (
                                SELECT Id FROM DT_Rule_Criteria__r
                            )
                        FROM 
                            DT_Rule_Version__c
                        WHERE
                            Id =: objRuleCriteria.DT_Rule_Version__c];
                            
                            //System.debug('RuleVer--->' +DT_Rule_Version__c.DT_Rule__r.DT_Target_SObject_API_Name__c);
        
        //If active then show message while editing
        if(ruleVersion.DT_IsActive__c){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, System.Label.DT_LABEL_DEACTIVATE_RULE));
            bShowError = true;
            return;
        } else if(ruleVersion.DT_Deactivated_Date__c != NULL){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'You cannot edit the components once the Rule is deactivated. Please create a clone to use.'));
            bShowError = true;
            return;
        }

        if(ruleVersion.DT_Rule__r.DT_Rule_Type__c.equals(DT_Constants.DT_RULE_TYPE_TASK))
        {
            bTaskType = true;
            System.debug('<<task type>>'+ruleVersion.DT_Rule__r.DT_Rule_Type__c.equals(DT_Constants.DT_RULE_TYPE_TASK));

        }

        System.debug(bTaskType);
        
        System.debug('ruleVersion.DT_Rule__r.DT_Rule_Type__c : ' + ruleVersion.DT_Rule__r.DT_Rule_Type__c);
        
        //Populate Task Fields
        //lstTaskFields = new List<SelectOption>{new SelectOption(DT_Constants.DT_EMPTY, DT_Constants.DT_NONE)};
        lstTaskFields = new List<SelectOption>();
        lstTaskFields.addAll(populateSObjectFields(DT_Constants.DT_OBJECT_TASK));
        
        //Populate Target Sobejct Fields
        lstTargetObjectFields = populateSObjectFields(ruleVersion.DT_Rule__r.DT_Target_SObject_API_Name__c);
        
        Map<Id, Schema.RecordTypeInfo> mapRTbyId = Schema.SObjectType.DT_Rule_Criterion__c.getRecordTypeInfosById();
        if(mapRTbyId.containsKey(selectedVal)){ 
            Schema.RecordTypeInfo selectedRTInfo =  mapRTbyId.get(selectedVal);
            selectedRTName = selectedRTInfo.getName();
        }
        enableDisableTaskField();
        
    }
    
    /* enableDisableTaskField 
     * Action support method for enabling and disabling task and value compare field
     * @params : Not Applicable
     * @return : null
     */
    public PageReference enableDisableTaskField() {
        System.debug('selectedRTName>>' + selectedRTName);
        if(DT_Constants.DT_RECORD_TYPE_MAP_SOBJECT.equals(selectedRTName))
        {
            bShowTask = true;
            bShowMapValue = false;
            bShowValueCompare = false;
            bShowSourceField = true;
            bShowDueDate = false;

        }else if(DT_Constants.DT_RECORD_TYPE_COMPARE.equals(selectedRTName)){
            bShowTask = false;
            bShowMapValue = false;
            bShowValueCompare = true;
            bShowSourceField =true;
            bShowDueDate = false;

        }else if(DT_Constants.DT_RECORD_TYPE_MAP_STATIC.equals(selectedRTName)){
            bShowTask = true;
            bShowMapValue = true;
            bShowValueCompare = false;
            bShowSourceField = false;
            bShowDueDate = false;

            if(objRuleCriteria.DT_Target_Task_Field__c == DT_Constants.DT_FIELD_DUE_DATE){
                sDaysToAdd = objRuleCriteria.DT_Value_to_Map__c;
                bShowDueDate = true;
                bShowMapValue = false;
            }
        }

        return null;
    }

    /* populateSObjectFields 
     * Populate the sobject fileds based on the object API Name
     * @params : strObjName
     * @return : List<SelectOption> lstSObjectFields
     */
    public List<SelectOption> populateSObjectFields(String strObjName){
        
        List<SelectOption> lstSObjectFields = new List<SelectOption>(); 
        
        try {
        
            //Populate the sObject Fields
            System.debug('strObjName>>' + strObjName);
            Map<String, Schema.SObjectField> mapObjectFields 
                    = Schema.getGlobalDescribe().get(strObjName).getDescribe().fields.getMap();
            
            //Return all the fields
            for(Schema.SObjectField fld :mapObjectFields.values()){
                schema.describeFieldResult dfield = fld.getDescribe();
                if(dfield.isUpdateable()
                    && dfield.isCreateable()){
                    
                    String sFieldName = dfield.getName();
                    if(!DT_Constants.DT_RESTRICTED_FIELDS.contains(sFieldName))        
                        lstSObjectFields.add(new SelectOption(sFieldName, dfield.getLabel()));
                }
            }
        
        } catch(Exception ex){
            //throw error
            System.debug('Exception on Class : DT_RuleCriteriaExtension - populateSObjectFields, Error : ' 
                            + ex.getMessage() 
                            + ' Line Number : ' 
                            + ex.getLineNumber()
                            + ' Cause : '
                            + ex.getCause()
                            + ' Type : '
                            + ex.getTypeName());
            
            bShowError = true;             
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.DT_LABEL_CONTACT_ADMIN));

            DT_Error_Log.genericException(
                            ex.getMessage(),
                            DT_Constants.DT_ERROR_TYPE_BUSINESS_VALIDATION,
                            ex, 
                            DT_Constants.DT_CLASS_RULE_CRITERIA_EXTENSION,
                            DT_Constants.DT_METHOD_POPULATE_OBJECT_FIELDS,
                            objRuleCriteria.Id == NULL ? NULL : objRuleCriteria.Id,
                            DT_Constants.DT_EMPTY);
            return NULL;
        }
        
        return lstSObjectFields;
    }
    

    
    /* save 
     * Override save method to save the record with additional custom values
     * @params :
     * @return :
     */
    public PageReference save(){
        
        try{
            //Show error if sObject field is NULL
            if(String.isBlank(objRuleCriteria.DT_Source_SObject_Field__c) && (DT_Constants.DT_RECORD_TYPE_MAP_SOBJECT.equals(selectedRTName)
                                || DT_Constants.DT_RECORD_TYPE_COMPARE.equals(selectedRTName)) ){
                bShowError = true;             
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.DT_LABEL_NO_FIELDS_SELECTED));
                return NULL;
            }


            objRuleCriteria.RecordTypeId = selectedVal;
            
            if(DT_Constants.DT_RECORD_TYPE_MAP_STATIC.equals(selectedRTName)){
                objRuleCriteria.DT_Source_SObject_Field_Type__c = DT_Constants.DT_EMPTY;
                objRuleCriteria.DT_Source_SObject_Field__c = DT_Constants.DT_EMPTY;
                objRuleCriteria.DT_Value_To_Compare__c = DT_Constants.DT_EMPTY;
                objRuleCriteria.DT_Operator__c = DT_Constants.DT_EMPTY;

               if(objRuleCriteria.DT_Target_Task_Field__c == DT_Constants.DT_FIELD_DUE_DATE){
                    objRuleCriteria.DT_Value_to_Map__c = sDaysToAdd;
                }
            }
            else if(DT_Constants.DT_RECORD_TYPE_MAP_SOBJECT.equals(selectedRTName)){
                objRuleCriteria.DT_Value_to_Map__c = DT_Constants.DT_EMPTY;
                objRuleCriteria.DT_Value_To_Compare__c = DT_Constants.DT_EMPTY;
                objRuleCriteria.DT_Operator__c = DT_Constants.DT_EMPTY;

                //Populate the data type of the field
                Schema.DisplayType dType 
                    = Schema.getGlobalDescribe().get(ruleVersion.DT_Rule__r.DT_Target_SObject_API_Name__c)
                    .getDescribe().fields.getMap().get(objRuleCriteria.DT_Source_SObject_Field__c)
                    .getDescribe().getType();
            
                objRuleCriteria.DT_Source_SObject_Field_Type__c = dType.name();
            }
            else if(DT_Constants.DT_RECORD_TYPE_COMPARE.equals(selectedRTName)){

                //Populate the data type of the field
                Schema.DisplayType dType 
                    = Schema.getGlobalDescribe().get(ruleVersion.DT_Rule__r.DT_Target_SObject_API_Name__c)
                    .getDescribe().fields.getMap().get(objRuleCriteria.DT_Source_SObject_Field__c)
                    .getDescribe().getType();
            
                objRuleCriteria.DT_Source_SObject_Field_Type__c = dType.name();
                objRuleCriteria.DT_Value_to_Map__c = DT_Constants.DT_EMPTY;  
                
                //Get only the compare rule criterias
                List<DT_Rule_Criterion__c> lstCompareCriteria = [SELECT DT_Rule_Version__c, 
                                        DT_Serial_Number__c, 
                                        Id,
                                        RecordTypeId FROM DT_Rule_Criterion__c 
                                        WHERE DT_Rule_Version__c =: objRuleCriteria.DT_Rule_Version__c 
                                        AND RecordType.Name  =: DT_Constants.DT_RECORD_TYPE_COMPARE];
                
                System.debug('<<This block>>'+objRuleCriteria.DT_Serial_Number__c);
                
                if(objRuleCriteria.DT_Serial_Number__c == null){
                    //auto populate the serial number for Compare Record Type
                    Set<Integer> setSlNos = new Set<Integer>();
                    objRuleCriteria.DT_Serial_Number__c = 1;
                    
                    for(DT_Rule_Criterion__c objRC : lstCompareCriteria){
                        setSlNos.add(Integer.valueOf(objRC.DT_Serial_Number__c));
                    }
                    Integer num = 1;
                    while(setSlNos.contains(num)){
                        objRuleCriteria.DT_Serial_Number__c = ++num;
                    }  
                }  
                
            }

            System.debug('<<This block>>'+objRuleCriteria.DT_Serial_Number__c);

            upsert objRuleCriteria;

        } catch(Exception ex){
            //throw error
            System.debug('Exception on Class : DT_RuleCriteriaExtension - save, Error : ' 
                            + ex.getMessage() 
                            + ' Line Number : ' 
                            + ex.getLineNumber()
                            + ' Cause : '
                            + ex.getCause()
                            + ' Type : '
                            + ex.getTypeName());
            
            bShowError = true;             
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.DT_LABEL_CONTACT_ADMIN));

            DT_Error_Log.genericException(
                            ex.getMessage(),
                            DT_Constants.DT_ERROR_TYPE_BUSINESS_VALIDATION,
                            ex, 
                            DT_Constants.DT_CLASS_RULE_CRITERIA_EXTENSION,
                            DT_Constants.DT_METHOD_SAVE,
                            objRuleCriteria.Id == NULL ? NULL : objRuleCriteria.Id,
                            DT_Constants.DT_EMPTY);
            return NULL;
        }
        
        return new PageReference(DT_Constants.DT_URL_VIEW_RULE_VERSION + '?id=' + objRuleCriteria.DT_Rule_Version__c);
    }
    
    
    /* deleteCriteria 
     * Delete Criteria and redirect to Rule Version View VF Page
     * @params :
     * @return : PageReference
     */
    public PageReference deleteCriteria(){
        try{
            //delete if it is not null
            if(objRuleCriteria != NULL){
                delete objRuleCriteria;
            }
            return new PageReference(DT_Constants.DT_URL_VIEW_RULE_VERSION + '?id=' + objRuleCriteria.DT_Rule_Version__c);
        }catch(Exception ex){
            DT_Error_Log.genericException(
                            ex.getMessage(),
                            DT_Constants.DT_ERROR_TYPE_BUSINESS_VALIDATION,
                            ex, 
                            DT_Constants.DT_CLASS_RULE_CRITERIA_EXTENSION,
                            DT_Constants.DT_METHOD_DELETE_RULE,
                            objRuleCriteria.Id == NULL ? NULL : objRuleCriteria.Id,
                            DT_Constants.DT_EMPTY);
            return null;
        }
    }

}