objects/DT_Rule__c.object
<CustomObject>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether the rule is Active based on the versions</description>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Rule_Type__c</fullName>
        <label>Rule Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                    <default>true</default>
                    <label>Task</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Target_SObject_API_Name__c</fullName>
        <description>API Name of the SObject which the rule is related to</description>
        <label>Target Object</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DT_Rule_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>DT_Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equals To</fullName>
                    <default>true</default>
                    <label>Equals To</label>
                </value>
                <value>
                    <fullName>Not Equals To</fullName>
                </value>
                <value>
                    <fullName>Greater Than</fullName>
                </value>
                <value>
                    <fullName>Greater Than Or Equals To</fullName>
                </value>
                <value>
                    <fullName>Less Than</fullName>
                </value>
                <value>
                    <fullName>Less Than Or Equals To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Rule_Version__c</fullName>
        <label>Rule Version</label>
        <referenceTo>DT_Rule_Version__c</referenceTo>
        <relationshipName>DT_Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DT_Serial_Number__c</fullName>
        <label>Serial Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DT_Source_SObject_Field_Type__c</fullName>
        <label>Source SObject Field Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Source_SObject_Field__c</fullName>
        <description>API Name of the sObject field to be considered for comparison or source sobject field to be copied to task object field</description>
        <label>Source SObject Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Target_Task_Field__c</fullName>
        <label>Target Task Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Value_To_Compare__c</fullName>
        <description>Value to compare with source sObject field</description>
        <inlineHelpText>Can have different formats
Date Format: YYYY-MM-DD</inlineHelpText>
        <label>Value To Compare</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Value_to_Map__c</fullName>
        <inlineHelpText>Can have different formats
Date Format: YYYY-MM-DD</inlineHelpText>
        <label>Value to Map</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Version_Source_Field_Comb__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Version ID + Sobject Field Combination to prevent users from adding the same criteria again</description>
        <externalId>true</externalId>
        <label>Version ID + Source Field</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rule Criterion</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Rule Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DT_Rule_Version__c.object
<CustomObject>
    <fields>
        <fullName>DT_Activated_Date__c</fullName>
        <label>Activated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DT_Assignee__c</fullName>
        <label>Assignee</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assign it back to the Submitted Person</fullName>
                </value>
                <value>
                    <fullName>Assign it to latest Task Owner</fullName>
                </value>
                <value>
                    <fullName>Assign it to latest Module Owner</fullName>
                </value>
                <value>
                    <fullName>Case Manager</fullName>
                    <isActive>false</isActive>
                    <label>Case Manager</label>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                    <isActive>false</isActive>
                    <label>Supervisor</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Criteria_Logic__c</fullName>
        <label>Criteria Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Deactivated_Date__c</fullName>
        <label>Deactivated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Landing Navigation</label>
        <referenceTo>DT_Landing_Navigation__c</referenceTo>
        <relationshipLabel>Rule Versions</relationshipLabel>
        <relationshipName>Rule_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DT_Queue_Name__c</fullName>
        <description>Contains the Developer Name field value of the Queue assigned</description>
        <label>Queue Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>DT_Rule__c</referenceTo>
        <relationshipName>DT_Rule_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DT_Version_Description__c</fullName>
        <label>Version Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DT_Version_Number__c</fullName>
        <description>Version Number in incremental for a single rule</description>
        <label>Version Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Rule Version</label>
    <nameField>
        <displayFormat>RV-{00000}</displayFormat>
        <label>Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DT_RuleVersionExtension.cls
/* Class Name   : DT_RuleVersionExtension
 * Description  :    
 * Created By   : Nidhin V K
 * Created On   : 07-28-2016

 * Modification Log:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date        Modification ID      Description 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K            07-28-2016        1000            Initial version
 * Debalina Chatterjee   09-22-2016        1001            Updated for displaying queue in Task rule version
 * Arya Parvathy         10-04-2016        1002            Made updates for enhanced task framework
 * Nidhin V K            12-Dec-2017       1003            CHanged manual picklist values to populate
 *
 */
public with sharing class DT_RuleVersionExtension {
    
    public List<SelectOption> lstQueues{get; set;}
    public List<SelectOption> lstAssignees{get; set;}
    public Boolean bShowQueue{get; set;}
    public Boolean bShowAssigneeType{get; set;}
    public Boolean bShowError{get; set;}
    public Boolean bError{get; set;}
    public Boolean bShowAssignees{get; set;}
    public DT_Rule_Version__c objRuleVer; //ruleVersion
    
    /* DT_RuleVersionExtensions 
     * constructor does the basic functionalities like checking Rule Type to show and hide Email/Queue fields
     * @params : ApexPages controller
     * @return : null
     */
    public DT_RuleVersionExtension(ApexPages.StandardController controller) { 
        if(!Test.isRunningTest())
        	controller.addFields(new List<String>{System.Label.DT_FIELD_RULE, System.Label.DT_FIELD_IS_ACTIVE, DT_Constants.DT_FIELD_DEACTIVATED_DATE });
        this.objRuleVer = (DT_Rule_Version__c)controller.getRecord();
        
        DT_Rule__c objRule = [SELECT id, 
                                  DT_Target_SObject_API_Name__c, 
                                  DT_Rule_Type__c,DT_IsActive__c 
                              FROM 
                                  DT_Rule__c 
                              WHERE 
                                  id=:objRuleVer.DT_Rule__c];

        AggregateResult arCriteria = [SELECT 
                                            Count(Id) RecordCount 
                                      FROM 
                                            DT_Rule_Version__c 
                                      WHERE 
                                            DT_Rule__c=:objRule.Id];
        
        if(String.isBlank(objRuleVer.Id)){
            objRuleVer.DT_Version_Number__c= Integer.valueOf(arCriteria.get('RecordCount')) + 1;
        } else if(objRuleVer.DT_Deactivated_Date__c != NULL){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'You cannot edit the Rule Version once deactivated. Please revise it.'));
            bShowError = true;
        }
        
        if(objRuleVer.DT_IsActive__c){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'You cannot edit the Rule Version once activated. Please revise or deactivate it.'));
            bShowError = true;
        }
        // hide fields based on Assignment Type
        if(String.isNotBlank(objRuleVer.DT_Assignment_Type__c)){
        	if(objRuleVer.DT_Assignment_Type__c.equals(System.Label.DT_RULE_VER_TYPE_MANUAL)){
        		bShowAssigneeType = true;
            	bShowQueue = false;
            	if(String.isNotBlank(objRuleVer.DT_Assignee__c)){
            		bShowAssignees = true;
            		if(objRuleVer.DT_Assignee__c.equals(DT_Constants.DT_ASSIGNEE_TYPE_TASK)){
        				lstAssignees = populateAssignees(DT_Constants.DT_FIELD_TASK_NAME);
            		} else if(objRuleVer.DT_Assignee__c.equals(DT_Constants.DT_ASSIGNEE_TYPE_MODULE)){
            			lstAssignees = populateAssignees(DT_Constants.DT_FIELD_MODULE);
            		} else{
            			bShowAssignees = false;
            		}
            	}
        	} else{
        		bShowQueue = true;
            	bShowAssigneeType = false;
        		lstQueues = populateQueues();
        	}
        }
    }
    
    /* onChangeAssignmentType 
     * on Change of AssignmentType
     * @params : 
     * @return : 
     */
    public void onChangeAssignmentType(){
    	if(String.isNotBlank(objRuleVer.DT_Assignment_Type__c)){
	    	if(objRuleVer.DT_Assignment_Type__c.equals(System.Label.DT_RULE_VER_TYPE_MANUAL)){
	    		bShowAssigneeType = true;
	        	bShowQueue = false;
	        	objRuleVer.DT_Assignee__c = DT_Constants.DT_ASSIGN_BACK_TO_PERSON;
	    	} else{
	    		bShowQueue = true;
	        	bShowAssigneeType = false;
	    		lstQueues = populateQueues();
	    	}
    	}
    }
    
    /* onChangeAssignmentType 
     * on Change of AssignmentType
     * @params : 
     * @return : 
     */
    public void onChangeAssigneeType(){
    	if(String.isNotBlank(objRuleVer.DT_Assignee__c)){
    		bShowAssignees = true;
    		if(objRuleVer.DT_Assignee__c.equals(DT_Constants.DT_ASSIGNEE_TYPE_TASK)){
				lstAssignees = populateAssignees(DT_Constants.DT_FIELD_TASK_NAME);
    		} else if(objRuleVer.DT_Assignee__c.equals(DT_Constants.DT_ASSIGNEE_TYPE_MODULE)){
    			lstAssignees = populateAssignees(DT_Constants.DT_FIELD_MODULE);
    		} else{
    			bShowAssignees = false;
    		}
    	}
    }

    /* toggleActivate 
     * method to Activate/ Deactivate a Rule Version
     * @params : null
     * @return : PageReference of Rule Version page
     */
    public PageReference toggleActivate(){
        try{
        	bError = false;
            if(objRuleVer != NULL){
                Integer iCount = [SELECT
	                                    Count()                                         
	                                FROM
	                                    DT_Rule_Criterion__c
	                                WHERE
	                                    DT_Rule_Version__c = :objRuleVer.Id];
                
                DT_Rule_Version__c  objVersion = [SELECT
                                                    Id,
                                                    DT_Rule__r.DT_IsActive__c
                                                FROM
                                                    DT_Rule_Version__c 
                                                WHERE
                                                    Id = :objRuleVer.Id];
                System.debug('iCount>>' + iCount);
                System.debug('objVersion>>' + objVersion);
                if(iCount < 1){ // Check if Rule Version has atleast one criteria
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.DT_LABEL_NO_CRITERIA_FOUND));
                    bShowError = true;
                    bError = true;
                    return null;
                }
                if(objVersion.DT_Rule__r.DT_IsActive__c == true){ //Check if Rule is Active
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.Label.DT_LABEL_DEACTIVATE_RULE));
                    bShowError = true;
                    bError = true;
                    return null;
                }                                           
            }
            System.debug('bError>>' + bError);
            if(bError == false){
                objRuleVer.DT_IsActive__c = objRuleVer.DT_IsActive__c ? false : true;
                if(objRuleVer.DT_IsActive__c){
            		System.debug('objRuleVer.DT_IsActive__c>>' + objRuleVer.DT_IsActive__c);
                    if(String.isBlank(objRuleVer.DT_Criteria_Logic__c)){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please provide the Criteria Logic.'));
                        bShowError = true;
                        objRuleVer.DT_IsActive__c = false;
                    } else{
                        if(DT_Util.checkCriteriaLogic(objRuleVer)){
                            objRuleVer.DT_Activated_Date__c = DateTime.now();
                        } else{
                            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Wrong Criteria Logic.'));
                            bShowError = true;
                            objRuleVer.DT_IsActive__c = false;
                        }
                    }
                } else{
                    objRuleVer.DT_Deactivated_Date__c = DateTime.now();
                }
                update objRuleVer;
                return NULL;
            }
            return NULL;
        }catch(Exception ex){
            //throw error
            String sId = DT_Error_Log.genericException(ex.getMessage(), 
                                                       System.Label.DT_ERROR_TYPE_VF_CONTROLLER, 
                                                       ex, 
                                                       System.Label.DT_CLASS_RULE_VERSION_EXTENSION , 
                                                       System.Label.DT_METHOD_TOGGLE_ACTIVATE, '', '');
            return NULL;
        }
    }

    /* populateQueues 
     * method to populate Queue field to select among all queues in the org.
     * @params : null
     * @return : List of SelectOption with Queues in the Org
     */
    public List<SelectOption> populateQueues(){
        List<SelectOption> lstQueues = new List<SelectOption>(); 
        for(Group objGrp :[SELECT Id, 
                             Name, 
                             DeveloperName 
                      FROM Group 
                      WHERE Type = 'Queue']){
                lstQueues.add(new SelectOption(objGrp.DeveloperName, objGrp.Name));
        }
        return lstQueues;
    }
    
    
    /* populateAssignees 
     * method to populate Tasks field to select among all queues in the org.
     * @params : null
     * @return : List of SelectOption with Queues in the Org
     */
    public List<SelectOption> populateAssignees(String sFieldName){
        List<SelectOption> lstAssignees = new List<SelectOption>(); 
        String sQuery = 'SELECT ' + sFieldName + ', count(Id) FROM DT_Rule__c WHERE DT_IsActive__c = true GROUP BY ' + sFieldName;
		System.debug('sQuery>>' + sQuery);
        for(AggregateResult agRule :Database.query(sQuery)){
				System.debug('agRule>>' + agRule);
				String sTaskName = String.valueOf(agRule.get(sFieldName));
				System.debug('sTaskName>>' + sTaskName);
                lstAssignees.add(new SelectOption(sTaskName, sTaskName));
        }
        return lstAssignees;
    }
    
     /* cloneVersion 
     * Clone Version and redirect to Rule Version View VF Page
     * @params : null
     * @return : PageReference to redirect to Rule Version VF page
     */
    public PageReference cloneVersion(){
        try {
		    if (objRuleVer != NULL) {
		        PageReference pgRuleVersion;
		
		        DT_Rule_Version__c objVersion = [SELECT ID, DT_Criteria_Logic__c, DT_Navigation__c, Name, DT_Assignment_Type__c, DT_Assignee__c, DT_Queue_Name__c, DT_Rule__c, DT_Version_Number__c, DT_Version_Description__c FROM DT_Rule_Version__c WHERE Id =: objRuleVer.Id];
		        DT_Rule_Version__c objVersionCopy = new DT_Rule_Version__c();
		        AggregateResult arVersionCount = [SELECT
										            Count(Id) RecordCount
										        FROM
										            DT_Rule_Version__c
										        WHERE
										            DT_Rule__c =: objVersion.DT_Rule__c];
		
		        objVersionCopy = objVersion.clone(false, true, false, false);
		        objVersionCopy.DT_Criteria_Logic__c = '';
		        objVersionCopy.DT_Version_Number__c = Integer.valueOf(arVersionCount.get('RecordCount')) + 1;
		        if (objVersionCopy != null) {
		            insert objVersionCopy;
		            List < DT_Rule_Criterion__c > lstRuleCriteria = new List < DT_Rule_Criterion__c > ();
		
		            for (DT_Rule_Criterion__c objCriteria: [SELECT ID, DT_Operator__c, DT_Serial_Number__c, DT_Source_SObject_Field__c, DT_Source_SObject_Field_Type__c, DT_Target_Task_Field__c, DT_Value_To_Compare__c, DT_Value_to_Map__c, DT_Version_Source_Field_Comb__c from DT_Rule_Criterion__c where DT_Rule_Version__c =: objRuleVer.Id]) {
		                DT_Rule_Criterion__c objCriteriaCopy = new DT_Rule_Criterion__c();
		                objCriteriaCopy = objCriteria.clone(false, true, false, false);
		                objCriteriaCopy.DT_Rule_Version__c = objVersionCopy.Id;
		                lstRuleCriteria.add(objCriteriaCopy);
		
		            }
		            if(lstRuleCriteria.size() > 0){
		            	insert lstRuleCriteria;
		            }
		            objVersionCopy.DT_Criteria_Logic__c = objVersion.DT_Criteria_Logic__c;
		            update objVersionCopy;
		            pgRuleVersion = new PageReference('/apex/DT_CreateRuleVersion?id=' + objVersionCopy.Id);
		            pgRuleVersion.setRedirect(true);
		            return pgRuleVersion;
		        }
		    } //if
		    return null;
		} catch (Exception ex) {
		    String sId = DT_Error_Log.genericException(ex.getMessage(),
		        System.Label.DT_ERROR_TYPE_BUSINESS_VALIDATION,
		        ex,
		        System.Label.DT_CLASS_RULE_VERSION_EXTENSION,
		        'CloneVersion', '', '');
		    return null;
		}
    
    }
    
    /* deleteVersion 
     * Delete Version and redirect to Rule Version View VF Page
     * @params : null
     * @return : PageReference to redirect to Rule VF page
     */
    public PageReference deleteVersion(){
        try{
            if(objRuleVer != null){
                delete objRuleVer;
            }
            return new PageReference(DT_Constants.DT_URL_VIEW_RULE + '?id=' + objRuleVer.DT_Rule__c);
        }catch(Exception ex){
            String sId = DT_Error_Log.genericException(ex.getMessage(), 
                                                       System.Label.DT_ERROR_TYPE_BUSINESS_VALIDATION, 
                                                       ex, 
                                                       System.Label.DT_CLASS_RULE_VERSION_EXTENSION , 
                                                       System.Label.DT_METHOD_DELETE_VERSION, '', '');
            return null;
        }
    }
    
}