objects/DT_Rule__c.object
<CustomObject>
    <fields>
        <fullName>DT_Active_Queue__c</fullName>
        <description>Will show the Queue value of the active version</description>
        <label>Active Queue</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether the rule is Active based on the versions</description>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Rule_Type__c</fullName>
        <label>Rule Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                    <default>true</default>
                    <label>Task</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Target_SObject_API_Name__c</fullName>
        <description>API Name of the SObject which the rule is related to</description>
        <label>Target Object</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DT_ViewRuleListController.cls
/* Class Name   : DT_ViewRuleListController
 * Description  :    
 * Created By   : Nidhin V K
 * Created On   : 08-04-2016

 * Modification Log:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date        Modification ID      Description 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K            08-04-2016        1000            Initial version
 * Debalina              10-05-2016        1001            Pagination
 *
 */
public with sharing class DT_ViewRuleListController {

    private Integer limitSize;

    public DT_ViewRuleListController() {
        limitSize = 1000;
    }
    
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT 
                        Id, 
                        Name, 
                        DT_Target_SObject_API_Name__c, 
                        DT_Rule_Type__c, 
                        DT_Priority__c, 
                        DT_IsActive__c,
                        DT_Active_Queue__c
                    FROM 
                        DT_Rule__c 
                    LIMIT :limitSize ]));

                setcon.setpagesize(20);
            }
            return setCon;
        }
        private set;
    }

    // Initialize setCon and return a list of records
    public List<DT_Rule__c> getRules() {

        setcon.setpagesize(20);
        return (List<DT_Rule__c>) setCon.getRecords();
    }
}