objects/DT_Rule__c.object
<CustomObject>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Shows whether the rule is Active based on the versions</description>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Module__c</fullName>
        <label>Module</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Rule_Type__c</fullName>
        <label>Rule Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Task</fullName>
                    <default>true</default>
                    <label>Task</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Target_SObject_API_Name__c</fullName>
        <description>API Name of the SObject which the rule is related to</description>
        <label>Target Object</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Task_Name__c</fullName>
        <label>Task Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DT_Rule_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>DT_Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Equals To</fullName>
                    <default>true</default>
                    <label>Equals To</label>
                </value>
                <value>
                    <fullName>Not Equals To</fullName>
                </value>
                <value>
                    <fullName>Greater Than</fullName>
                </value>
                <value>
                    <fullName>Greater Than Or Equals To</fullName>
                </value>
                <value>
                    <fullName>Less Than</fullName>
                </value>
                <value>
                    <fullName>Less Than Or Equals To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_Rule_Version__c</fullName>
        <label>Rule Version</label>
        <referenceTo>DT_Rule_Version__c</referenceTo>
        <relationshipName>DT_Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Criterion</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Rule Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DT_Rule_Version__c.object
<CustomObject>
    <fields>
        <fullName>DT_Assignment_Type__c</fullName>
        <label>Assignment Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manual</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Queue_Name__c</fullName>
        <description>Contains the Developer Name field value of the Queue assigned</description>
        <label>Queue Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>DT_Rule__c</referenceTo>
        <relationshipName>DT_Rule_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DT_Version_Number__c</fullName>
        <description>Version Number in incremental for a single rule</description>
        <label>Version Number</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Rule Version</label>
    <nameField>
        <displayFormat>RV-{00000}</displayFormat>
        <label>Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DT_Task__c.object
<CustomObject>
    <description>This object will act as a custom task object to store all tasks related to LTSS</description>
    <fields>
        <fullName>DT_Rule_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>To identify for which Rule version the task has been created</description>
        <label>Rule Version</label>
        <referenceTo>DT_Rule_Version__c</referenceTo>
        <relationshipName>LTSS_Task_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DT_Task_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchial Settings for all property values</description>
    <fields>
        <fullName>DT_Task_Master_Object__c</fullName>
        <label>Task Master Object API Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Task Settings</label>
</CustomObject>

src/classes/DT_TestDataFactory.cls
/***************************************************************************************************************************************
 * NAME   : DT_TestDataFactory
 * DESCRIPTION  : Contains all common test data records.
 *    
 * @AUTHOR   : Nidhin V K
 * @DATE   : 11-06-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K               11-06-2017          Initial version        
 *
 ****************************************************************************************************************************************/
@isTest
public with sharing class DT_TestDataFactory {
    
    
    public static DT_Rule__c createRule(Boolean isInsert){
        DT_Rule__c objRule = new DT_Rule__c(
                                Name = 'Test Rule', 
                                DT_Task_Name__c = 'Test Task', 
                                DT_Target_SObject_API_Name__c = 'Account',
                                DT_Module__c = 'Account',
                                DT_Rule_Type__c = DT_Constants.DT_RULE_TYPE_TASK,
                                DT_Priority__c = DT_Constants.DT_VALUE_NORMAL,
                                DT_IsActive__c = false);
                                
        if(isInsert)
            insert objRule;
        return objRule;
    }
    
    public static DT_Rule_Version__c createRuleVersion(Id ruleId, Boolean isInsert){
        if(String.isBlank(ruleId)){
            DT_Rule__c objRule = createRule(TRUE);
            ruleId = objRule.Id;
        }
        DT_Rule_Version__c objVersion = new DT_Rule_Version__c(  
                                DT_Rule__c = ruleId,
                                DT_Version_Number__c = 1,
                                DT_Assignment_Type__c = System.Label.DT_RULE_TYPE_QUEUE,
                                DT_Queue_Name__c = 'TestQueue',
                                DT_IsActive__c = false);
        
        if(isInsert)
            insert objVersion;
        return objVersion;
    }
    
    public static DT_Rule_Criterion__c createRuleCriteria(Id ruleId, Id versionId, Boolean isInsert){
        if(String.isBlank(versionId)){
            DT_Rule_Version__c objVersion = createRuleVersion(ruleId, TRUE);
            versionId = objVersion.Id;
        }
        DT_Rule_Criterion__c objCriterion = new DT_Rule_Criterion__c(  
                                DT_Rule_Version__c = versionId,
                                DT_Operator__c = DT_Constants.DT_STRING_EQUALS_TO);
        
        if(isInsert)
            insert objCriterion;
        return objCriterion;
    }
    
    public static DT_Task_Settings__c createTaskSettings(Boolean isInsert){
        DT_Task_Settings__c objSettings = new DT_Task_Settings__c(
                                            DT_Task_Master_Object__c = 'Account'
                                            );
        if(isInsert)
            insert objSettings;
        return objSettings;
    }
    
    public static RecordType createRecordType(Id recordId, String sObjectType){
        RecordType objRecordType = new RecordType(
                                        Id = recordId,
                                        Name = 'Sample RT',
                                        DeveloperName = 'SampleRT',
                                        IsActive = TRUE,
                                        SobjectType = sObjectType
                                            );
        return objRecordType;
    }
    
    public static void createQueue(){
        Group testGroup = new Group(Name='TestQueue', DeveloperName = 'TestQueue', Type='Queue');
        insert testGroup;
        System.runAs(new User(Id=UserInfo.getUserId())){
            QueuesObject testQueue = new QueueSObject(QueueID = testGroup.id, SObjectType = 'DT_Task__c');
            insert testQueue;
        }
    }
}