objects/DT_Rule__c.object
<CustomObject>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DT_Rule_Criterion__c.object
<CustomObject>
    <fields>
        <fullName>DT_Rule_Version__c</fullName>
        <label>Rule Version</label>
        <referenceTo>DT_Rule_Version__c</referenceTo>
        <relationshipName>DT_Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Criterion</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Rule Criterion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DT_Rule_Version__c.object
<CustomObject>
    <fields>
        <fullName>DT_Deactivated_Date__c</fullName>
        <label>Deactivated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DT_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DT_Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>DT_Rule__c</referenceTo>
        <relationshipName>DT_Rule_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Version</label>
    <nameField>
        <displayFormat>RV-{00000}</displayFormat>
        <label>Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DT_RuleCriterionTriggerHandler.cls
/* Class Name   : DT_RuleCriterionTriggerHandler
 * Description  :    
 * Created By   : Nidhin V K
 * Created On   : 07-26-2016

 * Modification Log:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Developer                Date        Modification ID      Description 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K            07-26-2016        1000            Initial version
 * Debalina              09-28-2016        1001
 *
 */
public class DT_RuleCriterionTriggerHandler{
    
    /* beforeDelete
     * Block users from doing delete rule criteria operation id rule or rule version is active
     * @params : mapRuleCriteria
     * @return : 
     *
    */
    public static void beforeDelete(Map<Id, DT_Rule_Criterion__c> mapRuleCriteria){
        
        //Get the Rule Details
        for(DT_Rule_Criterion__c criterion : [SELECT 
                                                Id, 
                                                DT_Rule_Version__r.DT_Rule__r.DT_IsActive__c,
                                                DT_Rule_Version__r.DT_IsActive__c,
                                                DT_Rule_Version__r.DT_Deactivated_Date__c
                                              FROM
                                                DT_Rule_Criterion__c
                                              WHERE
                                                Id IN :mapRuleCriteria.keySet()]){
            
            //Check for active rule
            if(criterion.DT_Rule_Version__r.DT_Rule__r.DT_IsActive__c){
                mapRuleCriteria.get(criterion.Id).addError(System.Label.DT_LABEL_DEACTIVATE_RULE);
            
            //Check for active version
            } else if(criterion.DT_Rule_Version__r.DT_IsActive__c
                || criterion.DT_Rule_Version__r.DT_Deactivated_Date__c != NULL){
                mapRuleCriteria.get(criterion.Id).addError(System.Label.DT_LABEL_DEACTIVATE_RULE_VERSION);
            }
        }
    }
}