src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Individual__c</fullName>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter Contact of Record Type Individual.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Master_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Task_Dashboard_Page_Size__c</fullName>
        <inlineHelpText>Values ranging from 3 to 10</inlineHelpText>
        <label>Task Dashboard Records Per Page</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task_Dashboard_Pages_Per_Screen__c</fullName>
        <inlineHelpText>Values ranging from 3 to 10</inlineHelpText>
        <label>Task Dashboard Pages Per Screen</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Master Settings</label>
</CustomObject>

src/objects/DT_Task__c.object
<CustomObject>
    <description>This object will act as a custom task object to store all tasks related to LTSS</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>DT Tasks</relationshipLabel>
        <relationshipName>DT_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DT Tasks</relationshipLabel>
        <relationshipName>LTSS_Task_Infos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DT_Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CC_Test_TasksComponentController.cls
/***************************************************************************************************************************************
 * NAME   : CC_Test_TasksComponentController
 * DESCRIPTION  : Test Class for CC_TasksComponentController.
 *    
 * @AUTHOR   : Nidhin V K
 * @DATE   : 11-16-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K               11-16-2017          Initial version        
 *
 ****************************************************************************************************************************************/

@isTest
private class CC_Test_TasksComponentController {
    @testSetup static void setupData() {
        List<Contact> lstContact = new List<Contact>();
        Integer iRecordSize = 200;
        for(Integer i = 0; i < iRecordSize; i++){
            Contact objContact = new Contact(LastName = 'Contact' + i);
            lstContact.add(objContact);
        }
        insert lstContact;
        List<Case> lstCase = new List<Case>();
        for(Integer i = 0; i < iRecordSize; i++){
                Case objCase = new Case(
                                Status = System.label.CC_Case_Status_Active
                                );
                lstCase.add(objCase);
        }
        insert lstCase;
        List<CC_Application__c> lstApp = new List<CC_Application__c>();
        for(Integer i = 0; i < iRecordSize; i++){
                CC_Application__c objApp = new CC_Application__c(
                                                CC_Individual__c = lstContact[i].Id,
                                                CC_Case__c = lstCase[i].Id
                                                                );
                lstApp.add(objApp);
        }
        insert lstApp;
        List<DT_Task__c> lstTask = new List<DT_Task__c>();
        Group objQueue = CC_TestDataFactory.createQueue();
        for(Integer i = 0; i < iRecordSize; i++){
                DT_Task__c objTask = new DT_Task__c(
                                        Name = 'Task' + i,
                                        DT_Status__c = DT_Constants.DT_TASK_STATUS_NEW,
                                        DT_Comments__c = 'Comment' + i,
                                        Contact__c = lstContact[i].Id,
                                        Case__c = lstCase[i].Id,
                                        OwnerId = objQueue.Id
                                                    );
                lstTask.add(objTask);
        }
        insert lstTask;
        CC_Master_Settings__c objSettings = new CC_Master_Settings__c(
                                                        Task_Dashboard_Page_Size__c = 10,
                                                        Task_Dashboard_Pages_Per_Screen__c = 10
                                                                    );
        insert objSettings;
    }
    
    @isTest static void testMethods() {
        String sQueueName = 'TestQueue';
        Test.startTest();
        Group ObjGroup = CC_Utility.getQueueInfo(sQueueName);
        System.debug('ObjGroup>>' + ObjGroup);
        System.assertEquals(ObjGroup.DeveloperName, sQueueName); 
        String sResult = CC_TasksComponentController.loadData(sQueueName, 'CreatedDate', 'DESC');
        System.debug('sResult|loadData>>' + sResult);
        System.assert(sResult.contains('CC_TASK_NAME'));
        sResult = CC_TasksComponentController.getMyTaskListAsString(ObjGroup.Id, 2, 'CreatedDate', 'DESC', '1', TRUE);
        System.debug('sResult|TaskListString>>' + sResult);
        System.assert(sResult.contains('Contact1'));
        Test.stopTest();
    }
}