src/objects/CC_Application_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Program_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Detail</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program Detail</value>
            </filterItems>
            <filterItems>
                <field>CC_Program_Service__c.Master_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Waiting_List_Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Program Detail Selections</relationshipLabel>
        <relationshipName>Application_Program_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Capacity Review Pending</fullName>
                </value>
                <value>
                    <fullName>Closed-Doesn&apos;t Meet Targeting Criteria</fullName>
                </value>
                <value>
                    <fullName>Waiver Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reserved</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Remove Wait-list</fullName>
                </value>
                <value>
                    <fullName>Closed-Disenrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waiting_List_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>All AD related to a Program which is waitlisted</description>
        <label>Waiting List Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Application Details(Related to Program)</relationshipLabel>
        <relationshipName>Application_Details_Prog</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Application Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Program_Service__c.object
<CustomObject>
    <fields>
        <fullName>Master_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Program Details</relationshipLabel>
        <relationshipName>Programs_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program &amp; Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs &amp; Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/DT_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>DT_Class_Method__c</fullName>
        <label>Class Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DT_Error_Type__c</fullName>
        <label>Error Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Apex Trigger</fullName>
                </value>
                <value>
                    <fullName>Business Validation</fullName>
                </value>
                <value>
                    <fullName>Component</fullName>
                </value>
                <value>
                    <fullName>DML Errors</fullName>
                </value>
                <value>
                    <fullName>Integration Batch Job</fullName>
                </value>
                <value>
                    <fullName>Integration Inbound</fullName>
                </value>
                <value>
                    <fullName>Integration Outbound</fullName>
                </value>
                <value>
                    <fullName>Apex Controller</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CC_Test_WaitlistPopoverController.cls
/***************************************************************************************************************************************
 * NAME   : CC_Test_WaitlistPopoverController
 * DESCRIPTION  : Waitlist popover grid  Controller
 *    
 * @AUTHOR   : Akshay Mohan
 * @DATE   : 18-Dec-2017
 * 
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER				DATE				DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Akshay Mohan				18-Dec-2017			Initial version   
 ****************************************************************************************************************************************/
@isTest
public class CC_Test_WaitlistPopoverController {
	@testSetup//set up contact and application
    public static void setUpData() {
        String sAppId = CC_TestDataFactory.createNewIndividualApp('Test Guy','Male','123456789',Date.newInstance(1999, 10 , 21))[2];
        System.debug('sAppId: ' + sAppId);
        
        List<String> lstProgDetail = new List<String>();
        lstProgDetail.add('Regular:50');
        lstProgDetail.add('Urgent:100');
        CC_Program_Service__c objProg = CC_TestDataFactory.createProgram('Intensive Supports',lstProgDetail);
        System.debug('objProg: ' + objProg);
        lstProgDetail = new List<String>();
        lstProgDetail.add('Emergency:60');
        lstProgDetail.add('Urgent:200');
        objProg = CC_TestDataFactory.createProgram('Comprehensive Supports',lstProgDetail);
		System.debug('objProg: ' + objProg);
        
        CC_Application_Detail__c objAppDetail = CC_TestDataFactory.createProgramSelection(sAppId,objProg.Id);
        System.debug('objAppDetail: ' + objAppDetail);
    }
    
    @isTest
    public static void loadWithProgram(){
        
        CC_Program_Service__c objProg = [SELECT ID,Name FROM CC_Program_Service__c WHERE Name='Comprehensive Supports'];
        System.debug('objProg: ' + objProg);
        
        Test.startTest();
        String sResult1 = CC_WaitlistPopoverController.loadData(objProg.Id,null);
        CC_Application_Detail__c objAppDetail = [SELECT ID,Status__c,Waiting_List_Program__c FROM CC_Application_Detail__c limit 1];
        objAppDetail.Status__c = System.Label.CC_PGM_STATUS_WAITLISTED;
        update objAppDetail;
        String sResult2 = CC_WaitlistPopoverController.refreshGrid(objProg.Id,null);
        Test.stopTest();
        
        String sJSONPrefix ='{"lstWaitList" : ',sJSONSuffix = '}';
        String sJSON = CC_TestDataFactory.getJSONToDesirialize(sResult1,sJSONPrefix,sJSONSuffix);
        System.debug('sJSON: ' + sJSON);
        List<CC_WaitlistPopoverController.WaitlistWrapper> lstWaitList = (List<CC_WaitlistPopoverController.WaitlistWrapper>)
            															JSON.deserialize(sJSON, List<CC_WaitlistPopoverController.WaitlistWrapper>.class);
        
        System.debug('lstWaitList: ' + lstWaitList);
        System.assertEquals(0, lstWaitList.size(),'Waitlist retrieved when no present');
        
        sJSON = CC_TestDataFactory.getJSONToDesirialize(sResult2,sJSONPrefix,sJSONSuffix);
        System.debug('sJSON: ' + sJSON);
        lstWaitList = (List<CC_WaitlistPopoverController.WaitlistWrapper>)
            			JSON.deserialize(sJSON, List<CC_WaitlistPopoverController.WaitlistWrapper>.class);
        
        System.debug('lstWaitList: ' + lstWaitList);
        System.assertEquals(1, lstWaitList.size(),'Waitlist not retrieved when present');
    }
    
    @isTest
    public static void loadWithProgramDetail(){
        
        CC_Program_Service__c objProgDetail = [SELECT ID,Name FROM CC_Program_Service__c 
                                         WHERE Master_Program__r.Name='Comprehensive Supports' limit 1];
        System.debug('objProgDetail: ' + objProgDetail);
        CC_Application_Detail__c objAppDetail = [SELECT ID,Status__c,Waiting_List_Program__c FROM CC_Application_Detail__c limit 1];
        objAppDetail.Status__c = System.Label.CC_PGM_STATUS_WAITLISTED;
        objAppDetail.Program_Detail__c = objProgDetail.Id;
        update objAppDetail;
        
        Test.startTest();
        String sResult = CC_WaitlistPopoverController.loadData(null,objProgDetail.Id);
        Test.stopTest();
        
        String sJSONPrefix ='{"lstWaitList" : ',sJSONSuffix = '}';
        String sJSON = CC_TestDataFactory.getJSONToDesirialize(sResult,sJSONPrefix,sJSONSuffix);
        System.debug('sJSON: ' + sJSON);
        List<CC_WaitlistPopoverController.WaitlistWrapper> lstWaitList = (List<CC_WaitlistPopoverController.WaitlistWrapper>)
            															JSON.deserialize(sJSON, List<CC_WaitlistPopoverController.WaitlistWrapper>.class);
        
        System.debug('lstWaitList: ' + lstWaitList);
        System.assertEquals(1, lstWaitList.size(),'Waitlist not retrieved when present');
        
       
    }

    @isTest
    public static void checkErrorLogging(){
        Test.startTest();
        String sResult = CC_WaitlistPopoverController.loadData(null,null);
        sResult = CC_WaitlistPopoverController.refreshGrid(null,null);
        Test.stopTest();
        System.debug('sResult: '+sResult);
        List<DT_Error_Log__c> lstErrors = [SELECT ID,DT_Class_Name__c,DT_Class_Method__c,DT_Error_Type__c 
                                            FROM DT_Error_Log__c WHERE DT_Class_Name__c<>null];
        System.assertEquals(2,lstErrors.size(),'Error not logged');
    }
}