src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_App_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Progress</fullName>
                    <default>true</default>
                    <label>In-Progress</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Revision Needed</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reviewed</fullName>
                    <isActive>false</isActive>
                    <label>Capacity Reviewed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Individual__c</fullName>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter Contact of Record Type Individual.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Master_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>App_Dashboard_Page_Size__c</fullName>
        <inlineHelpText>Values from 3 to 10</inlineHelpText>
        <label>App Dashboard Records Per Page</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>App_Dashboard_Pages_Per_Screen__c</fullName>
        <inlineHelpText>Values from 3 to 10</inlineHelpText>
        <label>App Dashboard Pages Per Screen</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task_Dashboard_Page_Size__c</fullName>
        <inlineHelpText>Values ranging from 3 to 10</inlineHelpText>
        <label>Task Dashboard Records Per Page</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task_Dashboard_Pages_Per_Screen__c</fullName>
        <inlineHelpText>Values ranging from 3 to 10</inlineHelpText>
        <label>Task Dashboard Pages Per Screen</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Master Settings</label>
</CustomObject>

classes/CC_Test_ApplicationsComponentController.cls
/***************************************************************************************************************************************
 * NAME   : CC_Test_ApplicationsComponentController
 * DESCRIPTION  : 
 * @AUTHOR   : Pankaj
 * @DATE   : 20-Nov-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Pankaj               20-Nov-2017          Initial version        
 *
 ****************************************************************************************************************************************/


@isTest
public class CC_Test_ApplicationsComponentController {
    
    @testSetup static void setupData() {
        List<Contact> lstContact = new List<Contact>();
        Integer iRecordSize = 200;
        for(Integer i = 0; i < iRecordSize; i++){
        	Contact objContact = new Contact(LastName = 'Contact' + i);
        	lstContact.add(objContact);
        }
        insert lstContact;
       
        List<CC_Application__c> lstApp = new List<CC_Application__c>();
        for(Integer i = 0; i < iRecordSize; i++){
                CC_Application__c objApp = new CC_Application__c(
                    							CC_App_Status__c = System.Label.CC_AppStatus_InProgress,
                                                CC_Individual__c = lstContact[i].Id
                                                            );
                lstApp.add(objApp);
        }
        insert lstApp;
        CC_Master_Settings__c objSettings = new CC_Master_Settings__c(
        												App_Dashboard_Page_Size__c = 10,
        												App_Dashboard_Pages_Per_Screen__c = 10,
            											Task_Dashboard_Page_Size__c = 10,
        												Task_Dashboard_Pages_Per_Screen__c = 10
        															);
        insert objSettings;
    }
    
    @isTest static void testMethods() {
    	Test.startTest();
    	String sResult = CC_ApplicationsComponentController.loadData( 'CreatedDate', 'DESC');
    	System.debug('sResult|loadData>>' + sResult);
    	System.assert(sResult.contains('CC_APP_NUMBER'));
    	sResult = CC_ApplicationsComponentController.getMyAppListAsString( 2, 'CreatedDate', 'DESC', '1', TRUE);
    	System.debug('sResult|TaskListString>>' + sResult);
    	System.assert(sResult.contains('Contact1'));
        Test.stopTest();
    }

}