src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_App_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Progress</fullName>
                    <default>true</default>
                    <label>In-Progress</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Revision Needed</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reviewed</fullName>
                    <isActive>false</isActive>
                    <label>Capacity Reviewed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_How_soon_services_needed__c</fullName>
        <label>How soon are the services needed?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Immediately (health and safety)</fullName>
                </value>
                <value>
                    <fullName>More than a year</fullName>
                </value>
                <value>
                    <fullName>Within 1 year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Individual__c</fullName>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter Contact of Record Type Individual.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CC_On_Any_Waiver_Waiting_List__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On Any Waiver Waiting List?</label>
        <type>Checkbox</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Application_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Getting_the_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Getting the Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Program_Name__c</fullName>
        <description>For Waitlist Record Type this stores Waitlisted Other Program Name
For Service Detail Record Type this stores Other Getting Program Name</description>
        <label>Other Program Currently Getting/Waitlist</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Service_Name__c</fullName>
        <label>Other Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Application__c</fullName>
        <label>Related Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Application Details</relationshipLabel>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Service</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Application Details (Related To Service)</relationshipLabel>
        <relationshipName>Application_Details_Serv</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Waiting_List_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>All AD related to a Program which is waitlisted</description>
        <label>Waiting List Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Application Details(Related to Program)</relationshipLabel>
        <relationshipName>Application_Details_Prog</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Application Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Program_Service__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies if Program is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Agency</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program &amp; Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs &amp; Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CC_Contact_County__c</fullName>
        <label>CC_Contact_County</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CC_Physical_Address_State__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CC_County</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Mailing_Address_County__c</fullName>
        <label>Mailing Address County</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CC_Mailing_Address_State__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CC_County</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Mailing_Address_State__c</fullName>
        <label>Mailing Address State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CC_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Physical_Address_State__c</fullName>
        <label>Physical Address State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_SSN__c</fullName>
        <label>Social Security Number (SSN)</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Suffix__c</fullName>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JR.</fullName>
                </value>
                <value>
                    <fullName>SR.</fullName>
                </value>
                <value>
                    <fullName>II</fullName>
                </value>
                <value>
                    <fullName>III</fullName>
                </value>
                <value>
                    <fullName>IV</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>VI</fullName>
                </value>
                <value>
                    <fullName>VII</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CC_Test_ServiceController.cls
@isTest
public class CC_Test_ServiceController {

@testSetup
public static void setUpData() {
		//CC_TestDataFactory.setUpServiceData();
	}
	static testMethod void loadAndSaveServiceData() {

		User userServiceIntake = [SELECT Id FROM User where Profile.Name =: 
								  System.label.CC_Self_Service_Intake_Profile AND IsActive = TRUE LIMIT 1];
		User userAppintake = [SELECT Id FROM User where Profile.Name =: 
								System.label.CC_App_Intake_Profile AND IsActive = TRUE LIMIT 1];
		User userCaseManager = [SELECT Id FROM User where Profile.Name =: 
								System.label.CC_Case_Manager_Profile AND IsActive = TRUE LIMIT 1];

			List<String> lstProgram = new List<String>{'Acquired Brain Injury Supports',
    													'Comprehensive Adult Supports',
    													'Intensive Supports',
    													'Other',
    													'Residential Supports'};
    		List<CC_Program_Service__c> lstProgtoInsert = new List<CC_Program_Service__c>();

    		for(String str : lstProgram){
    			CC_Program_Service__c objProg = new CC_Program_Service__c();
    			objProg.recordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_PROGRAM_SERVICE_OBJ, System.label.CC_RT_Program);
    			objProg.Name = str;
    			objProg.Active__c = true;
    			//objProg.Agency__c = acc.id;

    			lstProgtoInsert.add(objProg);
    		}
    		insert lstProgtoInsert;

    		CC_Program_Service__c objService = new CC_Program_Service__c();
    		objService.recordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_PROGRAM_SERVICE_OBJ, System.label.CC_RT_Service);
    		objService.Program__c = lstProgtoInsert[0].id;
    		objService.Active__c = true;
    		insert objService;

			Contact objContact = new Contact();
			objContact.Birthdate =  Date.newInstance(1999, 10 , 21);
			objContact.FirstName = 'TestFirstName1'.toUpperCase();
			objContact.LastName = 'TestLastName1'.toUpperCase();
			objContact.CC_Gender__c = 'Male';
			objContact.CC_Suffix__c = 'II';
			objContact.CC_SSN__c = '888888888';
			objContact.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Individual);
			objContact.CC_Physical_Address_State__c = 'Other';
			objContact.CC_Mailing_Address_State__c = 'Other';
			objContact.CC_Contact_County__c = 'Other';
			objContact.CC_Mailing_Address_County__c = 'Other';
			insert objContact;

			CC_Application__c objApp = new CC_Application__c();
			objApp.CC_Individual__c = objContact.Id;
			objApp.CC_App_Status__c = System.label.CC_AppStatus_InProgress;
			objApp.CC_How_soon_services_needed__c = 'More than a year';
			objApp.CC_On_Any_Waiver_Waiting_List__c = false;
			insert objApp;

			List<CC_Application_Detail__c> appDetToInsert = new List<CC_Application_Detail__c>();

			CC_Application_Detail__c objAppDetP1 = new CC_Application_Detail__c();
			objAppDetP1.Related_Application__c = objApp.Id;
			objAppDetP1.Service__c = objService.id;
			objAppDetP1.recordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ,System.label.CC_RT_Service_Type);

			CC_Application_Detail__c objAppDetP2 = new CC_Application_Detail__c();
			objAppDetP2.Related_Application__c = objApp.Id;
			objAppDetP2.Service__c = objService.id;
			objAppDetP2.recordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ,System.label.CC_RT_Service_Type);
			
			CC_Application_Detail__c objAppDetW1 = new CC_Application_Detail__c();
			objAppDetW1.Related_Application__c = objApp.Id;
			objAppDetW1.Waiting_List_Program__c = lstProgtoInsert[0].id;
			objAppDetW1.recordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ,System.label.CC_RT_Waitlist_Type);
			
			appDetToInsert.add(objAppDetP1);
			appDetToInsert.add(objAppDetP2);
			appDetToInsert.add(objAppDetW1);

			insert appDetToInsert;

			CC_Application_Detail__c objAppDetP3 = new CC_Application_Detail__c();
			objAppDetP3.Related_Application__c = objApp.Id;
			objAppDetP3.Service__c = objService.id;
			objAppDetP3.Getting_the_Service__c = true;
			objAppDetP3.Other_Program_Name__c = 'Test';
			objAppDetP3.Other_Service_Name__c = 'Test';
			objAppDetP3.Service_Needed__c = false;
        
        	String strObj = JSON.serialize(objAppDetP3);

			List<Id> lstAppToDel = new List<Id>();
			lstAppToDel.add([Select id from CC_Application_Detail__c where
											recordTypeId =: CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ,System.label.CC_RT_Waitlist_Type)
											 LIMIT 1].id);

			objApp.CC_How_soon_services_needed__c = 'Within 1 year';
			objApp.CC_On_Any_Waiver_Waiting_List__c = true;
			update objApp;



			String sOtherComment = 'TestComment';
			List<String> lstSelectedWaitList = new List<String>{'Acquired Brain Injury Supports',
    														'Comprehensive Adult Supports',
    														'Other'};
            Test.startTest();
            
            System.runAs(userServiceIntake){
	            map<String,String> mapLabels = CC_ServicesController.loadLabelAndError();
				String strLoadData = CC_ServicesController.getPageDataForApplication(objApp.id);
				CC_ServicesController.updateApplication(objApp,sOtherComment,lstSelectedWaitList);
				String returnValDel = CC_ServicesController.deleteAppDetail(lstAppToDel,objApp.Id);
				String returnValAdd = CC_ServicesController.addAppDetail(strObj);
			}
			
			System.runAs(userAppintake){
				map<String,String> mapLabels = CC_ServicesController.loadLabelAndError();
				String strLoadData = CC_ServicesController.getPageDataForApplication(objApp.id);
				CC_ServicesController.updateApplication(objApp,sOtherComment,lstSelectedWaitList);
				String returnValDel = CC_ServicesController.deleteAppDetail(lstAppToDel,objApp.Id);
				String returnValAdd = CC_ServicesController.addAppDetail(strObj);
			}
			
			System.runAs(userCaseManager){
				map<String,String> mapLabels = CC_ServicesController.loadLabelAndError();
				String strLoadData = CC_ServicesController.getPageDataForApplication(objApp.id);
				CC_ServicesController.updateApplication(objApp,sOtherComment,lstSelectedWaitList);
				String returnValDel = CC_ServicesController.deleteAppDetail(lstAppToDel,objApp.Id);
				String returnValAdd = CC_ServicesController.addAppDetail(strObj);
			}
			Test.stopTest();
	}
}