src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_Does_Individual_have_Auth_Rep__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Does Individual have Auth Rep</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CC_Where_does_the_individual_live__c</fullName>
        <label>Where does the individual live?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1-2 Bed Adult Family Home (certified)</fullName>
                </value>
                <value>
                    <fullName>Foster Care</fullName>
                </value>
                <value>
                    <fullName>Group home</fullName>
                </value>
                <value>
                    <fullName>Group Residential Care Setting - Assisted Living</fullName>
                </value>
                <value>
                    <fullName>Group Residential Care Setting - Licensed Adult Family Care Home</fullName>
                </value>
                <value>
                    <fullName>Home/apartment for which lease is held by support services provider</fullName>
                </value>
                <value>
                    <fullName>Homeless shelter</fullName>
                </value>
                <value>
                    <fullName>Hospice Care Facility</fullName>
                </value>
                <value>
                    <fullName>ICF/IDD (Intermediate Care Facility)</fullName>
                </value>
                <value>
                    <fullName>Jail</fullName>
                </value>
                <value>
                    <fullName>Living in own home or apartment</fullName>
                </value>
                <value>
                    <fullName>Living with a friend</fullName>
                </value>
                <value>
                    <fullName>Living with family/relative</fullName>
                </value>
                <value>
                    <fullName>No Permanent Residence</fullName>
                </value>
                <value>
                    <fullName>Nursing home</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other Paid caregiver&apos;s home</fullName>
                </value>
                <value>
                    <fullName>Personal care home</fullName>
                </value>
                <value>
                    <fullName>Psychiatric Facility</fullName>
                </value>
                <value>
                    <fullName>Receives Public Housing Assistance</fullName>
                </value>
                <value>
                    <fullName>Rents Home/Apartment</fullName>
                </value>
                <value>
                    <fullName>Someone Else&apos;s Home or Apartment</fullName>
                </value>
                <value>
                    <fullName>Staffer Home</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_individual_have_LegalGuardian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Does the individual have LegalGuardian</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visited_Pages__c</fullName>
        <label>Visited Pages</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contact Information</fullName>
                </value>
                <value>
                    <fullName>Representative Information</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Living Situation</fullName>
                </value>
                <value>
                    <fullName>Documents</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CC_Document_Validation__mdt.object
<CustomObject>
    <description>This setting manages the required configuration data for document upload</description>
    <fields>
        <fullName>Document_Types__c</fullName>
        <label>Document Types</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mandatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needed_Document__c</fullName>
        <label>Needed Document</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Document Validation</label>
    <pluralLabel>Document Validations</pluralLabel>
</CustomObject>

src/objects/CC_Module__mdt.object
<CustomObject>
    <description>Module object</description>
    <fields>
        <fullName>Document_Types__c</fullName>
        <label>Document Types</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Module</label>
    <pluralLabel>Modules</pluralLabel>
</CustomObject>

classes/CC_ApplicationDocumentUpload_Validator.cls
/***************************************************************************************************************************************
 * NAME   : CC_ApplicationDocumentUpload_Validator
 * DESCRIPTION  : Application Document Upload Validation method.
 *    
 * @AUTHOR   : Akshay Mohan
 * @DATE   : 11-11-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER				DATE				DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Akshay Mohan				11-11-2017			Initial version        
 ****************************************************************************************************************************************/

public class CC_ApplicationDocumentUpload_Validator implements CC_DocumentValidator_Interface{

    public String checkRequiredDocs(String sRecordId,String sDocListJSON){
    	System.debug('In checkRequiredDocs');
    	System.debug('sRecordId: ' + sRecordId);
    	System.debug('sDocListJSON: ' + sDocListJSON);
    	CC_Application__c objApp = [SELECT CC_Does_Individual_have_Auth_Rep__c, CC_individual_have_LegalGuardian__c, CC_Where_does_the_individual_live__c
    								FROM CC_Application__c WHERE ID =: sRecordId];
    	System.debug('objApp: ' + objApp);
    	Set<String> setDocs = (Set<String>) JSON.deserialize(sDocListJSON, Set<String>.class);
    	System.debug('setDocs: ' + setDocs);
    	Set<String> setReqDocKeys = new Set<String>();
    	if(objApp.CC_Does_Individual_have_Auth_Rep__c)
    		setReqDocKeys.add('AR_Proof');
    	if(objApp.CC_individual_have_LegalGuardian__c)
    		setReqDocKeys.add('LG_Proof');
    	if(objApp.CC_Where_does_the_individual_live__c == System.Label.CC_Application_Living_Currently_PF || 
    		objApp.CC_Where_does_the_individual_live__c == System.Label.CC_Application_Living_Currently_ICF ||
    		objApp.CC_Where_does_the_individual_live__c == System.Label.CC_Application_Living_Currently_NH)
    		setReqDocKeys.add('LS_WhereDoYouLive');
    	System.debug('setReqDocKeys: ' + setReqDocKeys);

    	Boolean bFound;
    	List<CC_FileUpload_Controller.RequiredDocumentWrapper> lstReqDocs = new List<CC_FileUpload_Controller.RequiredDocumentWrapper>();
    	for(CC_Document_Validation__mdt objVal : [SELECT Needed_Document__c,Document_Types__c,Mandatory__c FROM CC_Document_Validation__mdt
    													WHERE DeveloperName IN :setReqDocKeys]){
    		bFound = false;
    		for(String sDocType : objVal.Document_Types__c.split(','))
    			if(setDocs.contains(sDocType)){
    				bFound=true;
    				break;
    			}

    		lstReqDocs.add(new CC_FileUpload_Controller.RequiredDocumentWrapper(objVal.Needed_Document__c, objVal.Document_Types__c,
    																				objVal.Mandatory__c,bFound));
    	}
    		
    	System.debug('lstReqDocs: ' + lstReqDocs);
        return JSON.serialize(lstReqDocs);
    }

    public String getDocUploadPicklistValues(String sModule){
    	System.debug('In getDocUploadPicklistValues');
    	System.debug('sModule: ' + sModule);
    	CC_Module__mdt objModule = [SELECT Document_Types__c FROM CC_Module__mdt WHERE DeveloperName =:sModule];
    	System.debug('objModule: ' + objModule);
    	List<String> lstValues = objModule.Document_Types__c.split(',');
    	System.debug('lstValues: ' + lstValues);
    	return JSON.serialize(CC_Utility.getPicklistValuesWrapper(System.Label.CC_Select_Document_Type,lstValues));
    }

    public void setPageVisited(String sRecordId){
        CC_Application__c objApp = [SELECT ID,Visited_Pages__c FROM CC_Application__c WHERe Id = :sRecordId];
        objApp.Visited_Pages__c = CC_Utility.setTabName(System.label.CC_Documents_Tab, objApp.Visited_Pages__c);
        System.debug('objApp: ' + objApp);
        update objApp;
    }
        
}