src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Application_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Enrolled_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enrolled Program</label>
        <referenceTo>CC_Enrolled_Program__c</referenceTo>
        <relationshipLabel>Application Details</relationshipLabel>
        <relationshipName>Application_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Detail</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program Detail</value>
            </filterItems>
            <filterItems>
                <field>CC_Program_Service__c.Master_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Waiting_List_Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Program Detail Selections</relationshipLabel>
        <relationshipName>Application_Program_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Application__c</fullName>
        <label>Related Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Application Details</relationshipLabel>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Capacity Review Pending</fullName>
                </value>
                <value>
                    <fullName>Closed-Doesn&apos;t Meet Targeting Criteria</fullName>
                </value>
                <value>
                    <fullName>Waiver Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reserved</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Remove Wait-list</fullName>
                </value>
                <value>
                    <fullName>Closed-Disenrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waiting_List_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>All AD related to a Program which is waitlisted</description>
        <label>Waiting List Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Application Details(Related to Program)</relationshipLabel>
        <relationshipName>Application_Details_Prog</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Application Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CC_Enrolled_Program__c.object
<CustomObject>
    <fields>
        <fullName>Program_Detail__c</fullName>
        <label>Program Detail</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program Detail</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Enrolled Programs</relationshipLabel>
        <relationshipName>Enrolled_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Filled</fullName>
                </value>
                <value>
                    <fullName>Vacated</fullName>
                </value>
                <value>
                    <fullName>Freed</fullName>
                </value>
                <value>
                    <fullName>Closed-Denied LOC Assessment</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrolled Program</label>
    <nameField>
        <displayFormat>EP_{00000}</displayFormat>
        <label>Enrolled Program ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrolled Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Program_Service__c.object
<CustomObject>
    <label>Program &amp; Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs &amp; Services</pluralLabel>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>Waiver Program</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CC_AlternateProgramsController.cls
/***************************************************************************************************************************************
 * NAME   : CC_AlternateProgramsController
 * DESCRIPTION  : for CC_UrgencyComponent 
 *    
 * @AUTHOR : Debalina
 * @DATE   : 12-14-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER				DATE				DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Debalina				  12-14-2017			Initial version        
 ****************************************************************************************************************************************/

public without sharing class CC_AlternateProgramsController {

    public class CompWrapper{
        public String sId;
        public String sProgramName;
        public String sUrgencyReason;
        public String sStatus;
        public String sCategory;
        public String sAppNumber;
    }
/*****************************************************************************************************************************************/
	/* getPageData 
    * @params : sAppDetailId - Id of CC_Application_Detail__c containing info about current waiver program
    * @return : JSON String with all data and static values relevant to the page
    *****************************************************************************************************************************************/
	@AuraEnabled
    public static String getPageData(String sAppDetailId){
        List<CompWrapper> lstAlternateProg = new List<CompWrapper>();
        Map<String,String> mapLabelAndError = loadLabelAndError();

    	try {
        String sWaiverProgramTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ, System.label.CC_RT_Waiver_AppDetail);
        List<CC_Application_Detail__c> lstCurrentAppDetail = [SELECT Related_Application__r.CC_Case__r.Id
                                                             FROM CC_Application_Detail__c 
                                                             WHERE Id =: sAppDetailId];
        if(lstCurrentAppDetail.size() == 1){
            String sCaseId = lstCurrentAppDetail[0].Related_Application__r.CC_Case__r.Id;
            List<CC_Application_Detail__c> lstAppDetail = [ SELECT Id,
                                                               Status__c,
                                                               Reason__c,
                                                               Related_Application__r.Name,
                                                               Waiting_List_Program__r.Name,
                                                               Enrolled_Program__r.Program_Detail__r.Name
                                                        FROM CC_Application_Detail__c
                                                        WHERE Related_Application__r.CC_Case__r.Id =:sCaseId
                                                        AND RecordTypeId =: sWaiverProgramTypeId];
        
            for(CC_Application_Detail__c objAppDetail: lstAppDetail){
                if(objAppDetail.Id != sAppDetailId){
                    CompWrapper objWrap = new CompWrapper();
                    objWrap.sId = objAppDetail.Id;
                    objWrap.sAppNumber = objAppDetail.Related_Application__r.Name;
                    objWrap.sProgramName = objAppDetail.Waiting_List_Program__r.Name;
                    objWrap.sUrgencyReason = String.isNotBlank(objAppDetail.Reason__c)?
                                             objAppDetail.Reason__c : CC_Constants.CC_NO_DATA;
                    objWrap.sStatus = objAppDetail.Status__c;
                    objWrap.sCategory =  String.isNotBlank(objAppDetail.Enrolled_Program__r.Program_Detail__r.Name)?
                                         objAppDetail.Enrolled_Program__r.Program_Detail__r.Name : CC_Constants.CC_NO_DATA;
                    lstAlternateProg.add(objWrap);
                }
            }
        }
    	
        								    
        String sJSON = '{"lstAlternatePrograms":'+JSON.serialize(lstAlternateProg)
                        +',"MapLabelError":'+JSON.serialize(mapLabelAndError)
                        + '}';
        return JSON.serialize(new CC_ResponseWrapper(true, sJSON));
        
    	}catch(Exception ex){
            System.debug('Exception on Class : CC_AlternateProgramsController - getPageData, Error : ' +
            ex.getMessage() +
            ' Line Number : ' +
            ex.getLineNumber() +
            ' Cause : ' +
            ex.getCause() +
            ' Type : ' +
            ex.getTypeName());
            return JSON.serialize(new CC_ResponseWrapper(false, NULL, new List<String>{System.Label.DT_LABEL_CONTACT_ADMIN}));
        }
    }

        /******************************************************************************************************************************************/
    /* loadLabelAndError 
    * @params : N/A 
    * @return : Map of static values needed for the page
    /*****************************************************************************************************************************************/
    @TestVisible
    private static Map<String,String> loadLabelAndError() {
        Map<String,String> mapLabelAndError = new Map<String, String>();
        mapLabelAndError.put('CC_Urgency',System.label.CC_Urgency);
        mapLabelAndError.put('CC_Label_Program_Name',System.Label.CC_Label_Program_Name);
        mapLabelAndError.put('CC_LBL_Category',System.Label.CC_LBL_Category);
        mapLabelAndError.put('CC_LBL_Allocation_Status',System.Label.CC_LBL_Allocation_Status);
        mapLabelAndError.put('CC_LBL_NO_RECORD_EXIST',System.Label.CC_LBL_NO_RECORD_EXIST);
        mapLabelAndError.put('CC_LBL_Application',System.label.CC_LBL_Application);
        return mapLabelAndError;
    }	

}