src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_App_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Progress</fullName>
                    <default>true</default>
                    <label>In-Progress</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Revision Needed</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reviewed</fullName>
                    <isActive>false</isActive>
                    <label>Capacity Reviewed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Individual__c</fullName>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter Contact of Record Type Individual.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>IF( NOT( ISBLANK( Birthdate ) ) , 
IF( DATE( 2000 , MONTH( Birthdate ) , DAY( Birthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ), 
IF(YEAR (Today()) - YEAR ( Birthdate )== -1,0,YEAR (Today()) - YEAR ( Birthdate )), 
IF(YEAR (Today()) - YEAR ( Birthdate ) -1 == -1,0,YEAR (Today()) - YEAR ( Birthdate ) -1) ), 
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Middle_Initial__c</fullName>
        <label>Middle Initial</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_SSN__c</fullName>
        <label>Social Security Number (SSN)</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Suffix__c</fullName>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JR.</fullName>
                </value>
                <value>
                    <fullName>SR.</fullName>
                </value>
                <value>
                    <fullName>II</fullName>
                </value>
                <value>
                    <fullName>III</fullName>
                </value>
                <value>
                    <fullName>IV</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>VI</fullName>
                </value>
                <value>
                    <fullName>VII</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CC_IndividualInfoPopoverController.cls
/***************************************************************************************************************************************
 * NAME         : CC_IndividualInfoPopoverController
 * DESCRIPTION  : for  component  
 *    
 * @AUTHOR   : Debalina
 * @DATE     : 11-17-2017    
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Debalina               11-17-2017         Initial version        
 *
 ****************************************************************************************************************************************/


public without sharing class CC_IndividualInfoPopoverController {

    @AuraEnabled
    public static String getInfoData(String sAppId) {
        
        String sIndvRecTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Individual);
        List<CC_Application__c> lstAppl = [SELECT Id, 
                                           		    Name, 
                                                  CC_App_Status__c, 
                                                  CC_Case__c, 
                                                  CC_Individual__r.Id,
                                                  CC_Individual__r.FirstName, 
                                                  CC_Individual__r.LastName, 
                                                  CC_Individual__r.CC_Suffix__c,
                                                  CC_Individual__r.CC_Middle_Initial__c, 
                                                  CC_Individual__r.Birthdate, 
                                                  CC_Individual__r.CC_SSN__c ,
                                                  CC_Individual__r.CC_Gender__c ,
                                                  CC_Individual__r.Age__c
                                           FROM CC_Application__c 
                                           WHERE CC_Individual__r.RecordTypeId =: sIndvRecTypeId 
                                           AND Id =: sAppId LIMIT 1];
        
        CC_Application__c objApp = new CC_Application__c();
        if(lstAppl.size() == 1){
			      objApp = lstAppl[0];
            objApp.CC_App_Status__c = String.isNotBlank(objApp.CC_App_Status__c)? objApp.CC_App_Status__c : '';
            objApp.CC_Case__c = String.isNotBlank(objApp.CC_Case__c)? objApp.CC_Case__c : null;
            objApp.CC_Individual__r.CC_Suffix__c = String.isNotBlank(objApp.CC_Individual__r.CC_Suffix__c)? 
                				objApp.CC_Individual__r.CC_Suffix__c : '';
 			      objApp.CC_Individual__r.CC_Middle_Initial__c = String.isNotBlank(objApp.CC_Individual__r.CC_Middle_Initial__c)? 
                										   objApp.CC_Individual__r.CC_Middle_Initial__c : '';
            objApp.CC_Individual__r.CC_SSN__c = String.isNotBlank(objApp.CC_Individual__r.CC_SSN__c)? 
                										   objApp.CC_Individual__r.CC_SSN__c : '';

        }

        Map<String,String> mapLabelAndError = loadLabelAndError();
        return '{"Application":'+JSON.serialize(objApp)
                +',"MapLabelError":'+JSON.serialize(mapLabelAndError)
                +'}';	
    }

    @TestVisible
    private static Map<String,String> loadLabelAndError() {
      Map<String,String> mapLabelAndError = new Map<String, String>();
     
      mapLabelAndError.put('CC_LBL_DOB',System.label.CC_LBL_DOB);
      mapLabelAndError.put('CC_LBL_Gender',System.label.CC_LBL_Gender);
      mapLabelAndError.put('CC_Label_Close',System.label.CC_Label_Close);

      mapLabelAndError.put('CC_LBL_Status',System.label.CC_LBL_Status);
      mapLabelAndError.put('CC_LBL_Application',System.label.CC_LBL_Application);
      mapLabelAndError.put('CC_LBL_AGE',System.label.CC_LBL_AGE);
      mapLabelAndError.put('CC_Label_EnrolledProgram',System.label.CC_Label_EnrolledProgram);
      mapLabelAndError.put('CC_Label_Case',System.label.CC_Label_Case);
      mapLabelAndError.put('CC_Label_LocEndDate',System.label.CC_Label_LocEndDate);
      mapLabelAndError.put('CC_Label_CaseManager',System.label.CC_Label_CaseManager);
      mapLabelAndError.put('CC_Label_CaseSupervisor',System.label.CC_Label_CaseSupervisor);
      mapLabelAndError.put('CC_Label_CaseManagementAgency',System.label.CC_Label_CaseManagementAgency);
      mapLabelAndError.put('CC_Label_CaseManagerContact',System.label.CC_Label_CaseManagerContact);
      mapLabelAndError.put('CC_Label_ProgramSelected',System.label.CC_Label_ProgramSelected);
      mapLabelAndError.put('CC_IndividualInformation',System.label.CC_IndividualInformation);
      mapLabelAndError.put('CC_CaseMangementInformation',System.label.CC_CaseMangementInformation);
      mapLabelAndError.put('CC_SelectedPrograms',System.label.CC_SelectedPrograms);
      mapLabelAndError.put('CC_ProgramName',System.label.CC_ProgramName);

      return mapLabelAndError;
    }
}