src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_Individual__c</fullName>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter Contact of Record Type Individual.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Application_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Program_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Detail</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program Detail</value>
            </filterItems>
            <filterItems>
                <field>CC_Program_Service__c.Master_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Waiting_List_Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Program Detail Selections</relationshipLabel>
        <relationshipName>Application_Program_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Application__c</fullName>
        <label>Related Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Application Details</relationshipLabel>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Capacity Review Pending</fullName>
                </value>
                <value>
                    <fullName>Closed-Doesn&apos;t Meet Targeting Criteria</fullName>
                </value>
                <value>
                    <fullName>Waiver Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reserved</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Remove Wait-list</fullName>
                </value>
                <value>
                    <fullName>Closed-Disenrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waiting_List_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>All AD related to a Program which is waitlisted</description>
        <label>Waiting List Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Application Details(Related to Program)</relationshipLabel>
        <relationshipName>Application_Details_Prog</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Application Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Program_Service__c.object
<CustomObject>
    <fields>
        <fullName>Master_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Program Details</relationshipLabel>
        <relationshipName>Programs_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program &amp; Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs &amp; Services</pluralLabel>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>Waiver Program</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CC_WaitlistPopoverController.cls
/***************************************************************************************************************************************
 * NAME   : CC_WaitlistPopoverController
 * DESCRIPTION  : Waitlist popover grid  Controller
 *    
 * @AUTHOR   : Akshay Mohan
 * @DATE   : 18-Dec-2017
 * 
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER				DATE				DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Akshay Mohan				18-Dec-2017			Initial version   
 ****************************************************************************************************************************************/
public class CC_WaitlistPopoverController {
	private static String sClassName = 'CC_WaitlistPopoverController' ;
	
	public class WaitlistWrapper{
		public String sName, sUrgency;
		public WaitlistWrapper(CC_Application_Detail__c objProgram){
			sName = objProgram.Related_Application__r.CC_Individual__r.LastName;
			if(String.isNotBlank(objProgram.Related_Application__r.CC_Individual__r.FirstName))
				sName+=', '+objProgram.Related_Application__r.CC_Individual__r.FirstName;
			sUrgency = objProgram.Waiting_List_Program__r.Name;
		}
	}
	

	/* loadData 
    * Gets the data required to load the Component
    * @params : sProgramId, Record Id for Program 
    * @params : sProgramDetailID, Program Detail Id
    * 
    * @return : a JSON of the page data
    */
	@AuraEnabled
	public static String loadData(String sProgramId, String sProgramDetailID) {
		CC_ResponseWrapper wrapResponse = new CC_ResponseWrapper();
        String sMethodName = 'loadData';
		try{
			
	        System.debug('sProgramId: ' + sProgramId);
	        System.debug('sProgramDetailID: ' + sProgramDetailID);
			List<WaitlistWrapper> lstWaitList = loadWaitlist(sProgramId,sProgramDetailID);
			System.debug('lstWaitList: ' + lstWaitList);
			String sQuery = 'SELECT Id,Name FROM CC_Program_Service__c WHERE ';
			if(String.isNotBlank(sProgramId))
				sQuery+=' Master_Program__c= : sProgramId ';
			else
				sQuery+=' ID =: sProgramId ';
			System.debug('sQuery: ' + sQuery);
			
			List<CC_PickListValue_Wrapper> lstProgramDetails = new List<CC_PickListValue_Wrapper>();
			lstProgramDetails.add(new CC_PickListValue_Wrapper(null,System.Label.CC_Waitlisted_Popover_Select));
			for(CC_Program_Service__c objProgramDetail : Database.query(sQuery))
				lstProgramDetails.add(new CC_PickListValue_Wrapper(objProgramDetail.Id,objProgramDetail.Name));
			System.debug('lstProgramDetails: '+lstProgramDetails);
			
			Map<String,String> mapLabels = new Map<String,String>();
			mapLabels.put('CC_Waitlisted_Popover_Header',System.Label.CC_Waitlisted_Popover_Header);
			mapLabels.put('CC_Waitlisted_Popover_Filter_Section',System.Label.CC_Waitlisted_Popover_Filter_Section);
			mapLabels.put('CC_Waitlisted_Popover_Results_Section',System.Label.CC_Waitlisted_Popover_Results_Section);
			mapLabels.put('CC_LBL_Program_Name',System.Label.CC_LBL_Program_Name);
			mapLabels.put('CC_LBL_Category',System.Label.CC_LBL_Category);
			mapLabels.put('CC_INDIVIDUAL_NAME',System.Label.CC_INDIVIDUAL_NAME);
			mapLabels.put('CC_Waitlisted_Popover_No_Individuals',System.Label.CC_Waitlisted_Popover_No_Individuals);
			mapLabels.put('CC_SEARCH',System.Label.CC_SEARCH);

			wrapResponse.response= '{"lstWaitList" : '+JSON.serialize(lstWaitList)+
									', "lstProgramDetails" : '+JSON.serialize(lstProgramDetails)+
									+', "mapLabels": '+JSON.serialize(mapLabels)+'}';
			wrapResponse.success= true;
		}catch(Exception e){
			DT_Error_Log.BusinessException(
	                sClassName+': '+sMethodName+'('+sProgramId+','+sProgramDetailID+')',
	                System.Label.DT_ERROR_TYPE_VF_CONTROLLER,
	                e.getMessage(),
	                e.getStackTraceString(),
	                sClassName,
	                sMethodName,
	                DT_Constants.DT_EMPTY,
	                DT_Constants.DT_EMPTY);
	        wrapResponse.success= false;
	        wrapResponse.response = e.getMessage();
		}
		return JSON.serialize(wrapResponse);
	}
    
    /* refreshGrid 
    * Gets the data required to load the Component
    * @params : sProgramId, Record Id for Program 
    * @params : sProgramDetailID, Program Detail Id
    * 
    * @return : a JSON of the waitlist grid
    */
	@AuraEnabled
	public static String refreshGrid(String sProgramId, String sProgramDetailID) {
		CC_ResponseWrapper wrapResponse = new CC_ResponseWrapper();
        String sMethodName = 'refreshGrid';
		try{
			System.debug('sProgramId: ' + sProgramId);
	        System.debug('sProgramDetailID: ' + sProgramDetailID);
			List<WaitlistWrapper> lstWaitList = loadWaitlist(sProgramId,sProgramDetailID);
			System.debug('lstWaitList: ' + lstWaitList);
			wrapResponse.response='{"lstWaitList" : '+JSON.serialize(lstWaitList)+'}';
			wrapResponse.success= true;
		}catch(Exception e){
			DT_Error_Log.BusinessException(
	                sClassName+': '+sMethodName+'('+sProgramId+','+sProgramDetailID+')',
	                System.Label.DT_ERROR_TYPE_VF_CONTROLLER,
	                e.getMessage(),
	                e.getStackTraceString(),
	                sClassName,
	                sMethodName,
	                DT_Constants.DT_EMPTY,
	                DT_Constants.DT_EMPTY);
	        wrapResponse.success= false;
	        wrapResponse.response = e.getMessage();
		}
        
		
		return JSON.serialize(wrapResponse);
    }
    
    /* loadWaitlist 
    * Gets the data required to load the Component
    * @params : sProgramId, Record Id for Program 
    * @params : sProgramDetailID, Program Detail Id
    * 
    * @return : a List<WaitlistWrapper>
    */
	public static List<WaitlistWrapper> loadWaitlist(String sProgramId, String sProgramDetailID) {
        String sWaitlistedStatus = System.Label.CC_PGM_STATUS_WAITLISTED;
		String sQuery='SELECT Related_Application__r.CC_Individual__r.FirstName, Related_Application__r.CC_Individual__r.LastName'
							+', Waiting_List_Program__r.Name, Reason__c FROM CC_Application_Detail__c WHERE Status__c = :sWaitlistedStatus AND ';
		if(String.isNotBlank(sProgramDetailID)){
			sQuery+=' Program_Detail__c = :sProgramDetailID ';
		}else if(String.isNotBlank(sProgramId)){
			sQuery+=' Waiting_List_Program__c = :sProgramId ';
		}
		System.debug('sQuery: ' + sQuery);
		List<WaitlistWrapper> lstWaitList = new List<WaitlistWrapper>();
		for(CC_Application_Detail__c objProgram : Database.query(sQuery))
			lstWaitList.add(new WaitlistWrapper(objProgram));
        return lstWaitList;
    }
}