src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_App_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Progress</fullName>
                    <default>true</default>
                    <label>In-Progress</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Revision Needed</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reviewed</fullName>
                    <isActive>false</isActive>
                    <label>Capacity Reviewed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Individual__c</fullName>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter Contact of Record Type Individual.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Application_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Related_Application__c</fullName>
        <label>Related Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Application Details</relationshipLabel>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Capacity Review Pending</fullName>
                </value>
                <value>
                    <fullName>Closed-Doesn&apos;t Meet Targeting Criteria</fullName>
                </value>
                <value>
                    <fullName>Waiver Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reserved</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Remove Wait-list</fullName>
                </value>
                <value>
                    <fullName>Closed-Disenrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Application Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Master_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>WL_App_List_Page_Size__c</fullName>
        <label>Waitlisted Apps Records Per Page</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WL_App_List_Pages_Per_Screen__c</fullName>
        <label>Waitlisted Apps Pages Per Screen</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Master Settings</label>
</CustomObject>

classes/CC_Test_WaitlistedApplicationListCtrlr.cls
/***************************************************************************************************************************************
 * NAME   : CC_Test_WaitlistedApplicationListCtrlr
 * DESCRIPTION  : Test Class for CC_WaitlistedApplicationListController
 * @AUTHOR   : Nidhin
 * @DATE   : 15-Dec-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin               15-Dec-2017          Initial version        
 *
 ****************************************************************************************************************************************/
@isTest
public class CC_Test_WaitlistedApplicationListCtrlr {
    
    @testSetup static void setupData() {
        List<Contact> lstContact = new List<Contact>();
        Integer iRecordSize = 50;
        for(Integer i = 0; i < iRecordSize; i++){
        	Contact objContact = new Contact(LastName = 'Contact' + i);
        	lstContact.add(objContact);
        }
        insert lstContact;
       
        List<CC_Application__c> lstApp = new List<CC_Application__c>();
        for(Integer i = 0; i < iRecordSize; i++){
                CC_Application__c objApp = new CC_Application__c(
                    							CC_App_Status__c = System.Label.CC_AppStatus_InProgress,
                                                CC_Individual__c = lstContact[i].Id
                                                            );
                lstApp.add(objApp);
        }
        insert lstApp;
        List<CC_Application_Detail__c> lstAppDetail = new List<CC_Application_Detail__c>();
        String sRecordTypeId =CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ, CC_Constants.CC_RECORD_TYPE_WAIVER_PROGRAMS);
        for(Integer i = 0; i < iRecordSize; i++){
                CC_Application_Detail__c objAppDetail = new CC_Application_Detail__c(
                    							Status__c = System.Label.CC_PGM_STATUS_WAITLISTED,
                                                Related_Application__c = lstApp[i].Id,
                                                RecordTypeId = sRecordTypeId
                                                            );
                lstAppDetail.add(objAppDetail);
        }
        insert lstAppDetail;
        CC_Master_Settings__c objSettings = new CC_Master_Settings__c(
        												WL_App_List_Page_Size__c = 3,
        												WL_App_List_Pages_Per_Screen__c = 3
        															);
        insert objSettings;
    }
    
    @isTest static void testMethods() {
    	Test.startTest();
    	String sResult = CC_WaitlistedApplicationListController.loadData( 'CreatedDate', 'DESC');
    	System.debug('sResult|loadData>>' + sResult);
    	System.assert(sResult.contains('CC_NO_APPLICATION'));
    	sResult = CC_WaitlistedApplicationListController.getMyAppListAsString( 2, 'CreatedDate', 'DESC', '1', TRUE);
    	System.debug('sResult|TaskListString>>' + sResult);
    	System.assert(sResult.contains('Contact1'));
        Test.stopTest();
    }

}