src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_App_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Progress</fullName>
                    <default>true</default>
                    <label>In-Progress</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Reviewed</fullName>
                </value>
                <value>
                    <fullName>Revision Needed</fullName>
                </value>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reviewed</fullName>
                    <isActive>false</isActive>
                    <label>Capacity Reviewed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Individual__c</fullName>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter Contact of Record Type Individual.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Waiver_App_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Waiver Application Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Selected_Program_Value__c</fullName>
        <label>Selected Program Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Waiver_Confirmation_Comments__c</fullName>
        <label>Waiver Confirmation Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Application_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Related_Application__c</fullName>
        <label>Related Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Application Details</relationshipLabel>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Capacity Review Pending</fullName>
                </value>
                <value>
                    <fullName>Closed-Doesn&apos;t Meet Targeting Criteria</fullName>
                </value>
                <value>
                    <fullName>Waiver Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reserved</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Remove Wait-list</fullName>
                </value>
                <value>
                    <fullName>Closed-Disenrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waiting_List_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>All AD related to a Program which is waitlisted</description>
        <label>Waiting List Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Application Details(Related to Program)</relationshipLabel>
        <relationshipName>Application_Details_Prog</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Application Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Document_Detail__c.object
<CustomObject>
    <description>Object to act as a wrapper to store the document specific wrapper details.</description>
    <fields>
        <fullName>Application_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Detail</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Application_Detail__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Waiver Programs</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Application_Detail__c</referenceTo>
        <relationshipLabel>Document Details</relationshipLabel>
        <relationshipName>Document_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Document Details</relationshipLabel>
        <relationshipName>Document_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Detail</label>
    <nameField>
        <displayFormat>DD-{000000}</displayFormat>
        <label>Document Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CC_Master_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CC_Customer_Support_Phone_Number__c</fullName>
        <label>Customer Support Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Master Settings</label>
</CustomObject>

src/objects/CC_Program_Service__c.object
<CustomObject>
    <label>Program &amp; Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs &amp; Services</pluralLabel>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <description>Waiver Program</description>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CC_WaiverConfirmationController.cls
/***************************************************************************************************************************************
 * NAME   : CC_WaiverConfirmationController
 * DESCRIPTION  : Controller Class for CC_WaiverConfirmation Component
 *
 * @AUTHOR   : Nidhin V K
 * @DATE   : 11-23-2017
 *
 * MODIFICATION LOG:  
 * --------------------------------------------------------------------------------------------------------------------------------------
 * DEVELOPER                DATE                DESCRIPTION 
 * --------------------------------------------------------------------------------------------------------------------------------------
 * Nidhin V K               11-23-2017          Initial version        
 *
 ****************************************************************************************************************************************/
public with sharing class CC_WaiverConfirmationController {
	public class ComponentWrapper {
		public String sAppId;
		public Boolean bIsComplete;
		public String sComments;
		public String sSuggestedProgramId;
		public Boolean bDisableYesRadio;
		public String sTaskToClose;
		public List<CC_PickListValue_Wrapper> lstPrograms;
		Map<String,String> mapLabels;
		public ComponentWrapper() {
			bDisableYesRadio = false;
			lstPrograms = new List<CC_PickListValue_Wrapper>();
			mapLabels = new Map<String,String>();
		}
	}
	
	/* METHOD NAME   : loadData
	 * DESCRIPTION  : load the records on page load
	 *
	 * RETURN TYPE   : list of items include labels, picklists
	 * PARAMETER   :         
	 */
	@AuraEnabled
	public static String loadData(String sAppId){
		try{
			ComponentWrapper wrapper = new ComponentWrapper();
			wrapper.mapLabels = loadLabelAndError();
			wrapper.sAppId = sAppId;
			wrapper.lstPrograms = getAllPrograms(sAppId);
			CC_Application__c objApp = [SELECT 
											Id, CC_Case__c, CC_Individual__c,
											Selected_Program_Value__c, Is_Waiver_App_Complete__c,
											Waiver_Confirmation_Comments__c
										FROM 
											CC_Application__c 
										WHERE 
											Id = :sAppId];
			wrapper.sComments = objApp.Waiver_Confirmation_Comments__c;
			wrapper.sSuggestedProgramId = objApp.Selected_Program_Value__c;
			wrapper.bIsComplete = objApp.Is_Waiver_App_Complete__c;
			for(CC_Document_Detail__c objDocDetail : [SELECT Id FROM CC_Document_Detail__c WHERE Status__c = :System.Label.CC_DOC_DETAIL_STATUS_INVALID AND Application__c = :sAppId]){
				wrapper.bIsComplete = false;
				wrapper.bDisableYesRadio = true;
				return JSON.serialize(new CC_ResponseWrapper(true, JSON.serialize(wrapper)));
			}
			return JSON.serialize(new CC_ResponseWrapper(true, JSON.serialize(wrapper)));
		}catch(Exception ex){
			//throw error no such field exists
			System.debug('Exception on Class : CC_TasksComponentController - loadData, Error : ' +
	                ex.getMessage() +
	                ' Line Number : ' +
	                ex.getLineNumber() +
	                ' Cause : ' +
	                ex.getCause() +
	                ' Type : ' +
	                ex.getTypeName());
			return JSON.serialize(new CC_ResponseWrapper(false, NULL, new List<String>{System.Label.DT_LABEL_CONTACT_ADMIN}));
	    }
	}
	
	/* METHOD NAME   : getAllPrograms
	 * DESCRIPTION  : return all the programs on page load
	 *
	 * RETURN TYPE   : program picklists
	 * PARAMETER   :         
	 */
	public static List<CC_PickListValue_Wrapper> getAllPrograms(String sAppId){
		List<CC_PickListValue_Wrapper> lstPrograms = new List<CC_PickListValue_Wrapper>();
		lstPrograms.add(new CC_PickListValue_Wrapper(CC_Constants.CC_EMPTY, CC_Constants.CC_EMPTY));
		for(CC_Program_Service__c objProgram : CC_TargetingCriteriaController.getAvailablePrograms(sAppId)){
			if(!objProgram.Name.equals('Other'))//temporary fix. Will remove once the services issues are resolved
				lstPrograms.add(new CC_PickListValue_Wrapper(objProgram.Id, objProgram.Name));
		}
		lstPrograms.add(new CC_PickListValue_Wrapper(CC_Constants.CC_NONE, System.Label.CC_NONE));
		lstPrograms.add(new CC_PickListValue_Wrapper(CC_Constants.CC_ALL_OPTIONS, System.Label.CC_IND_SEL_FOR_ALL_OPTNS));
		return lstPrograms;
	}
	
	/* METHOD NAME   : saveData
	 * DESCRIPTION  : save the records on save and exit
	 *
	 * RETURN TYPE   : 
	 * PARAMETER   :         
	 */
	@AuraEnabled
	public static String saveData(String sJSON){
		try{
			ComponentWrapper objWaiverInfo = (ComponentWrapper) JSON.deserialize(sJSON, ComponentWrapper.class);
			CC_Application__c objApp = new CC_Application__c();
			populateAppData(objWaiverInfo, objApp);
			update objApp;
			return JSON.serialize(new CC_ResponseWrapper(true, NULL, new List<String>{System.Label.CC_MSG_APP_SAVED_SUCCESS}));
		}catch(Exception ex){
			//throw error no such field exists
            System.debug('Exception on Class : CC_TasksComponentController - saveData, Error : ' +
	                ex.getMessage() +
	                ' Line Number : ' +
	                ex.getLineNumber() +
	                ' Cause : ' +
	                ex.getCause() +
	                ' Type : ' +
	                ex.getTypeName());
			return JSON.serialize(new CC_ResponseWrapper(false, NULL, new List<String>{System.Label.DT_LABEL_CONTACT_ADMIN}));
	    }
	}
	
	/* METHOD NAME   : submitData
	 * DESCRIPTION  : submit the records on submit
	 *
	 * RETURN TYPE   : 
	 * PARAMETER   :         
	 */
	@AuraEnabled
	public static String submitData(String sJSON){
		try{
			List<String> lstMessages = new List<String>();
			ComponentWrapper objWaiverInfo = (ComponentWrapper) JSON.deserialize(sJSON, ComponentWrapper.class);
			//checking the document uploaded is reviewed
			for(CC_Document_Detail__c objDocDetail : [SELECT Id FROM CC_Document_Detail__c WHERE Status__c = NULL AND Application__c = :objWaiverInfo.sAppId]){
				return JSON.serialize(new CC_ResponseWrapper(false, NULL, NULL));
			}	
			CC_Application__c objApp = [SELECT 
											Id, Name, CC_Case__c, CC_Individual__c,
											CC_Individual__r.AccountId, CC_Individual__r.Email, 
											CreatedById, CreatedBy.Profile.Name
										FROM 
											CC_Application__c 
										WHERE 
											Id = :objWaiverInfo.sAppId];
			populateAppData(objWaiverInfo, objApp);
			System.debug('populateAppData objApp>>' + objApp);
			Case objCase = new Case(Id = objApp.CC_Case__c);
			CC_Application_Detail__c objAppDetail;
			if(objWaiverInfo.bIsComplete){
				if(objWaiverInfo.sSuggestedProgramId.equals(CC_Constants.CC_NONE)
					|| objWaiverInfo.sSuggestedProgramId.equals(CC_Constants.CC_ALL_OPTIONS)){
					
					objApp.CC_App_Status__c = System.Label.CC_AppStatus_Terminated;
					String sNetworkId, sNetworkName;
					if(!objApp.CreatedBy.Profile.Name.equals(System.Label.CC_App_Intake_Profile)){
						NetworkMember objMember = [SELECT Id, NetworkId, Network.Name FROM NetworkMember WHERE MemberId = :objApp.CreatedById];
						sNetworkId = objMember.NetworkId;
						sNetworkName = objMember.Network.Name;
						System.debug('objMember>>' + objMember);
					}
					
					//Post Notification
					CC_Utility.postNotificationFeed(objApp.CreatedById, sNetworkId, System.Label.CC_LBL_APP_REJECTED + ' (' + objApp.Name + '): ' + objWaiverInfo.sComments);

					if(String.isNotBlank(sNetworkName) && sNetworkName.equals(System.Label.CC_NETWORK_NAME_SELF_SERVICE)){
						//send mail
						if(String.isNotBlank(objApp.CC_Individual__r.Email))
							sendEmail(objApp);
					}
					update objApp;
					if(String.isNotBlank(objCase.Id)){
						objCase.Status = System.Label.CC_Case_Status_Closed;
						update objCase;
					}
					//close the prev task
					DT_Util.closePreviousAndCreateNewTask(NULL, objWaiverInfo.sTaskToClose);
					lstMessages.add(System.Label.CC_MSG_APP_TERMINATION_SUCCESS);
	        		return JSON.serialize(new CC_ResponseWrapper(true, NULL, lstMessages));
				}
				objCase.ContactId = objApp.CC_Individual__c;
				objCase.AccountId = objApp.CC_Individual__r.AccountId;
				objCase.Status = System.label.CC_Case_Status_Active;
				objCase.OwnerId = System.label.CC_Portal_Master_ID;
				upsert objCase;
				
				objApp.CC_Case__c = objCase.Id;
				objApp.CC_App_Status__c = System.Label.CC_APP_STATUS_REVIEWED;
				
				//create app detail
				objAppDetail = new CC_Application_Detail__c();
				objAppDetail.Waiting_List_Program__c = objWaiverInfo.sSuggestedProgramId;
				objAppDetail.Related_Application__c = objWaiverInfo.sAppId;
				objAppDetail.Status__c = CC_Constants.CC_APP_DTL_STATUS_PENDING;
				objAppDetail.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ, CC_Constants.CC_RECORD_TYPE_WAIVER_PROGRAMS);
				insert objAppDetail;
			} else{
				objApp.CC_App_Status__c = System.Label.CC_LBL_RevisionNeeded;
			}
			objApp.Waiver_Confirmation_Comments__c = '';
			update objApp;
			System.debug('Success objApp>>' + objApp);

			//call task f/w
			Map<String,String> mapTask = new Map<String,String>();
			mapTask.put('DT_Master_Record_Id__c', objApp.Id);
			mapTask.put('Application__c', objApp.Id);
			mapTask.put('Contact__c', objApp.CC_Individual__c);
			mapTask.put('DT_Comments__c', objWaiverInfo.sComments);

			DT_TaskResponseWrapper objResponse;
			if(objApp.CC_App_Status__c.equals(System.Label.CC_APP_STATUS_REVIEWED)){
				mapTask.put('Application_Detail__c', objAppDetail.Id);
				mapTask.put('Case__c', objApp.CC_Case__c);
				objResponse = DT_TaskAssignment.executeTaskRules(objAppDetail.Id, mapTask, objWaiverInfo.sTaskToClose);
				objCase = [SELECT CaseNumber FROM Case WHERE Id = :objCase.Id];
				lstMessages.add(System.Label.CC_MSG_APP_SUBMISSION_SUCCESS + ' ' + String.valueOf(objCase.CaseNumber));
			} else{
				objResponse = DT_TaskAssignment.executeTaskRules(objApp.Id, mapTask, objWaiverInfo.sTaskToClose);
				lstMessages.add(System.Label.CC_MSG_APP_REJECTED);
			}
			if(objResponse.success)
	        	return JSON.serialize(new CC_ResponseWrapper(true, NULL, lstMessages));
	        return JSON.serialize(new CC_ResponseWrapper(false, NULL, new List<String>{System.Label.DT_LABEL_CONTACT_ADMIN}));
		}catch(Exception ex){
			//throw error no such field exists
            System.debug('Exception on Class : CC_WaiverConfirmationController - saveData, Error : ' +
                ex.getMessage() +
                ' Line Number : ' +
                ex.getLineNumber() +
                ' Cause : ' +
                ex.getCause() +
                ' Type : ' +
                ex.getTypeName());
	        return JSON.serialize(new CC_ResponseWrapper(false, NULL, new List<String>{System.Label.DT_LABEL_CONTACT_ADMIN}));
	    }
	}
	
	/* METHOD NAME   : submitData
	 * DESCRIPTION  : submit the records on submit
	 *
	 * RETURN TYPE   : 
	 * PARAMETER   :         
	 */
	@AuraEnabled
	public static void populateAppData(ComponentWrapper objWaiverInfo, CC_Application__c objApp){
		objApp.Id = objWaiverInfo.sAppId;
		objApp.Waiver_Confirmation_Comments__c = objWaiverInfo.sComments;
		objApp.Selected_Program_Value__c = objWaiverInfo.sSuggestedProgramId;
		objApp.Is_Waiver_App_Complete__c = objWaiverInfo.bIsComplete;
	}
	
	/* METHOD NAME   : sendEmail
	 * DESCRIPTION  : send email
	 *
	 * RETURN TYPE   : 
	 * PARAMETER   :         
	 */
	public static void sendEmail(CC_Application__c objApp){
        EmailTemplate objTemplate = [SELECT id FROM EmailTemplate WHERE DeveloperName = 'CC_App_Rejection_Email'];
	        
        String sBody = Messaging.renderStoredEmailTemplate(objTemplate.Id, objApp.CC_Individual__c, objApp.Id).getHtmlBody();
        System.debug('Initial body: ' +sBody);
        sBody = sBody.substringBetween('<DIV>', '</DIV>');
        System.debug('Final body: ' +sBody);
        sBody = sBody.replace('(XXX) XXX-XXXX', CC_Master_Settings__c.getInstance().CC_Customer_Support_Phone_Number__c);
        
		Messaging.SingleEmailMessage objEMail = new Messaging.SingleEmailMessage();
		objEMail.toAddresses = new List<String>{objApp.CC_Individual__r.Email};
		//objEMail.setTemplateId(objTemplate.Id); 
		objEMail.setHtmlBody(sBody); 
		objEMail.setTargetObjectId(objApp.CC_Individual__c);
		objEMail.setWhatId(objApp.Id);
		objEMail.setSaveAsActivity(false);
		objEMail.setTreatTargetObjectAsRecipient(false);
		Messaging.SingleEmailMessage[] lstMessages = new List<Messaging.SingleEmailMessage> {objEMail};
        Messaging.SendEmailResult[] lstResults = Messaging.sendEmail(lstMessages);
    }
    
	/* METHOD NAME   : loadLabelAndError
	 * DESCRIPTION  : load the labels and errors for the page
	 *
	 * RETURN TYPE   : list of items include tasks list, labels, 
	 * PARAMETER   : sOwner        
	 */
	@TestVisible
	private static Map<String, String> loadLabelAndError() {
		Map<String, String> mapLabels = new Map<String, String>();
        mapLabels.put('CC_Save_Exit',System.Label.CC_Save_Exit);
        mapLabels.put('CC_Contact_SubmitButton',System.Label.CC_Contact_SubmitButton);
        mapLabels.put('CC_Back_Button',System.Label.CC_Back_Button);
        mapLabels.put('CC_Next_Button',System.Label.CC_Next_Button);
        mapLabels.put('CC_Tab_Complete_Icon',System.Label.CC_Tab_Complete_Icon);
        mapLabels.put('CC_Tab_Incomplete_Icon',System.Label.CC_Tab_Incomplete_Icon);
        mapLabels.put('CC_Application_Intake_Page',System.Label.CC_Application_Intake_Page);
        mapLabels.put('CC_Is_This_Waiver_Application_Complete',System.Label.CC_Is_This_Waiver_Application_Complete);
        mapLabels.put('CC_Waiver_Prog_Referred_To_Indiviual',System.Label.CC_Waiver_Prog_Referred_To_Indiviual);
        mapLabels.put('CC_LBL_COMMENTS_TO_APP_INITIATOR',System.Label.CC_LBL_COMMENTS_TO_APP_INITIATOR);
        mapLabels.put('CC_LBL_COMMENTS_TO_CAP_REVIEWER',System.Label.CC_LBL_COMMENTS_TO_CAP_REVIEWER);
        mapLabels.put('CC_CRITERIA_NOT_MEETING_REASON',System.Label.CC_CRITERIA_NOT_MEETING_REASON);
        mapLabels.put('CC_ERR_SELECT_A_PROGRAM',System.Label.CC_ERR_SELECT_A_PROGRAM);
        mapLabels.put('CC_ERR_GIVE_COMMENTS',System.Label.CC_ERR_GIVE_COMMENTS);
        mapLabels.put('CC_LBL_WAIVER_CONFIRMATION',System.Label.CC_LBL_WAIVER_CONFIRMATION);
        mapLabels.put('CC_NONE',CC_Constants.CC_NONE);
        mapLabels.put('CC_ALL_OPTIONS',CC_Constants.CC_ALL_OPTIONS);

		return mapLabels;
	}
}