src/objects/CC_Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Application_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Individual_Meet_Waiver_Criteria__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Individual Meet Waiver Criteria</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meet_For_Another_Waiver_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Meet For Another Waiver Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Application__c</fullName>
        <label>Related Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Application Details</relationshipLabel>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Waiting_List_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>All AD related to a Program which is waitlisted</description>
        <label>Waiting List Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Application Details(Related to Program)</relationshipLabel>
        <relationshipName>Application_Details_Prog</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Application Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Program_Service__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies if Program is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Program &amp; Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs &amp; Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CC_Test_AlternateProgramsController.cls
/***************************************************************************************************************************************
* NAME   : CC_Test_AlternateProgramsController
* DESCRIPTION  :   
*    
* @AUTHOR   : Debalina
* @DATE   : 12-12-2017
*
* MODIFICATION LOG:  
* --------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER                DATE                DESCRIPTION 
* --------------------------------------------------------------------------------------------------------------------------------------
* Debalina               12-12-2017            Initial version  
****************************************************************************************************************************************/
@isTest
public without sharing class CC_Test_AlternateProgramsController {
    
    public static String sAppId;
    
    @testSetup
    public static void setUpData() {
        sAppId = CC_TestDataFactory.createNewIndividualApp('Test Guy','Male','123456789',Date.newInstance(1999, 10 , 21))[2];
        System.debug('sAppId: ' + sAppId);
        CC_TestDataFactory.createUser(System.label.CC_Capacity_Reviewer_Profile);
        
        
    }
    static testmethod void testTargetingData(){
        List<CC_Application__c> lstApp = [SELECT ID FROM CC_Application__c];
        System.debug('lstApp: ' + lstApp);
        sAppId = lstApp[0].Id;
        
        CC_Program_Service__c objProg = new CC_Program_Service__c();
        objProg.recordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_PROGRAM_SERVICE_OBJ, System.label.CC_RT_Program);
        objProg.Name = 'Intensive Supports';
        objProg.Active__c = true;
        insert objProg;

        CC_Program_Service__c objProg2 = new CC_Program_Service__c();
        objProg2.recordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_PROGRAM_SERVICE_OBJ, System.label.CC_RT_Program);
        objProg2.Name = 'Comprehensive Adult Supports';
        objProg2.Active__c = true;
        insert objProg2;
        
        CC_Application_Detail__c objAppDetail = new CC_Application_Detail__c();
        objAppDetail.Related_Application__c = sAppId;
        objAppDetail.Waiting_List_Program__c = objProg.Id;
        objAppDetail.Individual_Meet_Waiver_Criteria__c = false;
        objAppDetail.Meet_For_Another_Waiver_Program__c = true;
        objAppDetail.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ, System.label.CC_RT_Waiver_AppDetail);
        insert objAppDetail;
        
        CC_Application_Detail__c objAppDetail2 = new CC_Application_Detail__c();
        objAppDetail2.Related_Application__c = sAppId;
        objAppDetail2.Waiting_List_Program__c = objProg2.Id;
        objAppDetail2.Individual_Meet_Waiver_Criteria__c = false;
        objAppDetail2.Meet_For_Another_Waiver_Program__c = true;
        objAppDetail2.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ, System.label.CC_RT_Waiver_AppDetail);
        insert objAppDetail2;
        
        Test.startTest();
        String sPageData = '';
        User capacityUser = [SELECT Id 
                             FROM User 
                             WHERE Profile.Name =: System.label.CC_Capacity_Reviewer_Profile LIMIT 1];
        System.runAs(capacityUser){
            sPageData = CC_AlternateProgramsController.getPageData(objAppDetail.Id);
            System.debug(sPageData);
        }
        
        Test.stopTest();
        System.assertEquals(sPageData!='',true);
        
    }
    
}