src/objects/CC_Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Application_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Capacity_Review_Action__c</fullName>
        <label>Capacity Review Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reserve Capacity</fullName>
                </value>
                <value>
                    <fullName>Add to Waitlist</fullName>
                </value>
                <value>
                    <fullName>Free Capacity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Individual_Meet_Waiver_Criteria__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Individual Meet Waiver Criteria</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meet_For_Another_Waiver_Program__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Meet For Another Waiver Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Detail</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program Detail</value>
            </filterItems>
            <filterItems>
                <field>CC_Program_Service__c.Master_Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Waiting_List_Program__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Program Detail Selections</relationshipLabel>
        <relationshipName>Application_Program_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Application__c</fullName>
        <label>Related Application</label>
        <referenceTo>CC_Application__c</referenceTo>
        <relationshipLabel>Application Details</relationshipLabel>
        <relationshipName>Application_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Capacity Review Pending</fullName>
                </value>
                <value>
                    <fullName>Closed-Doesn&apos;t Meet Targeting Criteria</fullName>
                </value>
                <value>
                    <fullName>Waiver Review</fullName>
                </value>
                <value>
                    <fullName>Capacity Reserved</fullName>
                </value>
                <value>
                    <fullName>Waitlisted</fullName>
                </value>
                <value>
                    <fullName>Remove Wait-list</fullName>
                </value>
                <value>
                    <fullName>Closed-Disenrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Waiting_List_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>All AD related to a Program which is waitlisted</description>
        <label>Waiting List Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Application Details(Related to Program)</relationshipLabel>
        <relationshipName>Application_Details_Prog</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Detail</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Application Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CC_Program_Service__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies if Program is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Master_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Program</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CC_Program_Service__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CC_Program_Service__c</referenceTo>
        <relationshipLabel>Program Details</relationshipLabel>
        <relationshipName>Programs_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program &amp; Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs &amp; Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DT_Task__c.object
<CustomObject>
    <description>This object will act as a custom task object to store all tasks related to LTSS</description>
    <fields>
        <fullName>Application_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Detail</label>
        <referenceTo>CC_Application_Detail__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CC_Test_Manage_Allotment.cls
@isTest
public class CC_Test_Manage_Allotment {
    
    public static String sAppId;

    @testSetup
    public static void setUpData() {
        
        
        sAppId = CC_TestDataFactory.createNewIndividualApp('Test Guy','Male','123456789',Date.newInstance(1999, 10 , 21))[2];
        System.debug('sAppId: ' + sAppId);

        CC_TestDataFactory.createUser(System.label.CC_Capacity_Reviewer_Profile);
    }
    
    static testmethod void testManageAllotmentData(){
        List<CC_Application__c> lstApp = [SELECT ID FROM CC_Application__c];
        System.debug('lstApp: ' + lstApp);
        sAppId = lstApp[0].Id;
        
        CC_Program_Service__c masterPrg= new CC_Program_Service__c();
        masterPrg.recordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_PROGRAM_SERVICE_OBJ, System.label.CC_RT_Program);
        masterPrg.Name = 'Comprehensive Adult Supports';
        masterPrg.Active__c = true;
        insert masterPrg;
        
        CC_Program_Service__c prgDetail= new CC_Program_Service__c();
        prgDetail.Name='Urgent';
        prgDetail.RecordTypeId=CC_Utility.getRecordTypeId(CC_Constants.CC_PROGRAM_SERVICE_OBJ, System.label.CC_RT_ProgramDetail);
        prgDetail.Active__c=true;
        prgDetail.Capacity__c=20;
        prgDetail.Master_Program__c=masterPrg.Id;
        insert prgDetail;
        
        CC_Application_Detail__c objAppDetail = new CC_Application_Detail__c();
        objAppDetail.Related_Application__c = sAppId;
        objAppDetail.Waiting_List_Program__c = masterPrg.Id;
        objAppDetail.Individual_Meet_Waiver_Criteria__c = false;
        objAppDetail.Meet_For_Another_Waiver_Program__c = false;
        objAppDetail.Program_Detail__c=prgDetail.Id;
        //objAppDetail.Status__c = System.label.CC_Status_Targeting_Criteria_Not_Met;
        objAppDetail.Capacity_Review_Action__c=System.Label.CC_LABEL_RESERVED_CAPACITY;
        objAppDetail.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_APP_DETAIL_OBJ, System.label.CC_RT_Waiver_AppDetail);
        insert objAppDetail;
        
        DT_Task__c objTask=new DT_Task__c();
        objTask.Name='Capacity Review';
        objTask.DT_Status__c='New';
        objTask.Application_Detail__c=objAppDetail.Id;
        insert objTask;
        
        Test.startTest();
        String sPageData = '';
        String sReturnValue = '';
        User capacityUser = [SELECT Id 
    							FROM User 
    						WHERE Profile.Name =: System.label.CC_Capacity_Reviewer_Profile LIMIT 1];
        
        System.runAs(capacityUser){
           // String sPageData = '';
            //String sReturnValue = '';
            //CC_ManageAllotmentController.WrapperGridValues objWrapGridValues;
            
            sPageData = CC_ManageAllotmentController.loadData(objAppDetail.Id);
            String sAppDetObj1=JSON.serialize(objAppDetail);
            sReturnValue=CC_ManageAllotmentController.doSave(sAppDetObj1,true,objTask.Id,masterPrg.Id);
            
            CC_Application_Detail__c objAppDetail2 = new CC_Application_Detail__c();
	        //objAppDetail2.Individual_Meet_Waiver_Criteria__c = false;
	        objAppDetail2.Meet_For_Another_Waiver_Program__c = false;
            objAppDetail2.Capacity_Review_Action__c=System.Label.CC_LABEL_ADD_TO_WAITLIST;
            objAppDetail2.Id = objAppDetail.Id;
	        update objAppDetail2;
            
            String sAppDetObj2=JSON.serialize(objAppDetail2);
            sReturnValue=CC_ManageAllotmentController.doSave(sAppDetObj2,true,objTask.Id,'');
            
             CC_Application_Detail__c objAppDetail3 = new CC_Application_Detail__c();
	        //objAppDetail2.Individual_Meet_Waiver_Criteria__c = false;
	        objAppDetail3.Meet_For_Another_Waiver_Program__c = true;
            objAppDetail3.Capacity_Review_Action__c=System.Label.CC_LABEL_ADD_TO_WAITLIST;
            objAppDetail3.Id = objAppDetail.Id;
	        update objAppDetail3;
            
            String sAppDetObj3=JSON.serialize(objAppDetail3);
            sReturnValue=CC_ManageAllotmentController.doSave(sAppDetObj3,true,objTask.Id,masterPrg.Id);
            
            
    }
        Test.stopTest();
        CC_ResponseWrapper objResponseWrap = (CC_ResponseWrapper) JSON.deserialize(sPageData, CC_ResponseWrapper.class);
        System.assertEquals(true,objResponseWrap.success);  
}
}