src/objects/CC_Application__c.object
<CustomObject>
    <fields>
        <fullName>CC_Does_Individual_have_Auth_Rep__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Does Individual have Auth Rep</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CC_Individual_Also_Your_Legal_Guardian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Individual Also Your Legal Guardian?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CC_Individual__c</fullName>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please enter Contact of Record Type Individual.</errorMessage>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>CC_Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CC_You_Your_Guardian_LiveAt_Same_Place__c</fullName>
        <defaultValue>false</defaultValue>
        <label>You and Your Guardian Live at Same Place</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CC_You_Your_Rep_LiveAt_Same_Place__c</fullName>
        <defaultValue>false</defaultValue>
        <label>You and Your Rep Live at Same Place?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CC_individual_have_LegalGuardian__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Does the individual have LegalGuardian</label>
        <type>Checkbox</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CC_Contact_County__c</fullName>
        <label>CC_Contact_County</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CC_Physical_Address_State__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CC_County</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Contact_Type__c</fullName>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Legal Guardian</fullName>
                </value>
                <value>
                    <fullName>Representative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Mailing_Address_County__c</fullName>
        <label>Mailing Address County</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CC_Mailing_Address_State__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>CC_County</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Mailing_Address_State__c</fullName>
        <label>Mailing Address State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CC_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_Physical_Address_State__c</fullName>
        <label>Physical Address State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CC_SSN__c</fullName>
        <label>Social Security Number (SSN)</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Suffix__c</fullName>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JR.</fullName>
                </value>
                <value>
                    <fullName>SR.</fullName>
                </value>
                <value>
                    <fullName>II</fullName>
                </value>
                <value>
                    <fullName>III</fullName>
                </value>
                <value>
                    <fullName>IV</fullName>
                </value>
                <value>
                    <fullName>V</fullName>
                </value>
                <value>
                    <fullName>VI</fullName>
                </value>
                <value>
                    <fullName>VII</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CC_Test_Representative_InfoController.cls
@isTest
public class CC_Test_Representative_InfoController {
    
    @testSetup static void setupData() {
    }
       
   static testMethod void loadAndSaveAppData1() {

		User userServiceIntake = [SELECT Id FROM User where Profile.Name =: 
								  System.label.CC_Self_Service_Intake_Profile AND IsActive = TRUE LIMIT 1];
		User userAppintake = [SELECT Id FROM User where Profile.Name =: 
								System.label.CC_App_Intake_Profile AND IsActive = TRUE LIMIT 1];
		
            
            Contact objContact = new Contact();
			objContact.Birthdate =  Date.newInstance(1999, 10 , 21);
			objContact.FirstName = 'TestFirstName1'.toUpperCase();
			objContact.LastName = 'TestLastName1'.toUpperCase();
			objContact.CC_Gender__c = 'Male';
			objContact.CC_Suffix__c = 'II';
			objContact.CC_SSN__c = '888888888';
			objContact.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Individual);
			objContact.CC_Physical_Address_State__c = 'Other';
			objContact.CC_Mailing_Address_State__c = 'Other';
			objContact.CC_Contact_County__c = 'Other';
			objContact.CC_Mailing_Address_County__c = 'Other';
            objContact.OwnerId=userServiceIntake.Id;
			insert objContact;
            
            Contact repobjContact = new Contact();
			repobjContact.Birthdate =  Date.newInstance(1999, 10 , 21);
			repobjContact.FirstName = 'TestFirstName1'.toUpperCase();
			repobjContact.LastName = 'TestLastName1'.toUpperCase();
			repobjContact.CC_Gender__c = 'Male';
			repobjContact.CC_Suffix__c = 'II';
			repobjContact.CC_SSN__c = '888888888';
            repobjContact.CC_Contact_Type__c=System.Label.CC_RT_Representative;
            repobjContact.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Representative);
			repobjContact.CC_Physical_Address_State__c = 'Other';
			repobjContact.CC_Mailing_Address_State__c = 'Other';
			repobjContact.CC_Contact_County__c = 'Other';
			repobjContact.CC_Mailing_Address_County__c = 'Other';
            repobjContact.OwnerId=System.Label.CC_Portal_Master_ID;
			insert repobjContact;
            
            Contact legobjContact = new Contact();
			legobjContact.Birthdate =  Date.newInstance(1999, 10 , 21);
			legobjContact.FirstName = 'TestFirstName1'.toUpperCase();
			legobjContact.LastName = 'TestLastName1'.toUpperCase();
			legobjContact.CC_Gender__c = 'Male';
            legobjContact.CC_Contact_Type__c=System.Label.CC_RT_Legal_Guardian;
            legobjContact.CC_Suffix__c = 'II';
			legobjContact.CC_SSN__c = '888888888';
			legobjContact.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Representative);
			legobjContact.CC_Physical_Address_State__c = 'Other';
			legobjContact.CC_Mailing_Address_State__c = 'Other';
			legobjContact.CC_Contact_County__c = 'Other';
			legobjContact.CC_Mailing_Address_County__c = 'Other';
            legobjContact.OwnerId=System.Label.CC_Portal_Master_ID;
			insert legobjContact;
            
            CC_Application__c objApp = new CC_Application__c();
			objApp.CC_Does_Individual_have_Auth_Rep__c = true;
			objApp.CC_individual_have_LegalGuardian__c = true;
			objApp.CC_Individual_Also_Your_Legal_Guardian__c=false;
			objApp.CC_You_Your_Guardian_LiveAt_Same_Place__c=true;
            objApp.CC_You_Your_Rep_LiveAt_Same_Place__c=true;
            objApp.CC_Individual__c=objContact.Id;
			insert objApp;
            
            String srepobjContact = JSON.serialize(repobjContact);
            String slegobjContact = JSON.serialize(legobjContact);
            String sobjApp = JSON.serialize(objApp);
            
            Test.startTest();
            
            System.runAs(userServiceIntake){
	            map<String,String> mapLabels = CC_Representative_InformationController.loadLabels();
				String strLoadData = CC_Representative_InformationController.loadContactData(objApp.id);
				String saveResult=CC_Representative_InformationController.doSave(srepobjContact,slegobjContact,sobjApp);
				
			}
           System.runAs(userAppintake){
	            map<String,String> mapLabels = CC_Representative_InformationController.loadLabels();
				String strLoadData = CC_Representative_InformationController.loadContactData(objApp.id);
				String saveResult=CC_Representative_InformationController.doSave(srepobjContact,slegobjContact,sobjApp);
            }		
			
            Test.stopTest();
            
    } 
    static testMethod void loadAndSaveAppData2() {

		
		User userAppintake = [SELECT Id FROM User where Profile.Name =: 
								System.label.CC_App_Intake_Profile AND IsActive = TRUE LIMIT 1];
		User userCaseManager = [SELECT Id FROM User where Profile.Name =: 
								System.label.CC_Case_Manager_Profile AND IsActive = TRUE LIMIT 1];
            
            Contact objContact = new Contact();
			objContact.Birthdate =  Date.newInstance(1999, 10 , 21);
			objContact.FirstName = 'TestFirstName1'.toUpperCase();
			objContact.LastName = 'TestLastName1'.toUpperCase();
			objContact.CC_Gender__c = 'Male';
			objContact.CC_Suffix__c = 'II';
			objContact.CC_SSN__c = '888888888';
			objContact.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Individual);
			objContact.CC_Physical_Address_State__c = 'Other';
			objContact.CC_Mailing_Address_State__c = 'Other';
			objContact.CC_Contact_County__c = 'Other';
			objContact.CC_Mailing_Address_County__c = 'Other';
            objContact.OwnerId=userCaseManager.Id;
			insert objContact;
            
            Contact repobjContact = new Contact();
			repobjContact.Birthdate =  Date.newInstance(1999, 10 , 21);
			repobjContact.FirstName = 'TestFirstName1'.toUpperCase();
			repobjContact.LastName = 'TestLastName1'.toUpperCase();
			repobjContact.CC_Gender__c = 'Male';
			repobjContact.CC_Suffix__c = 'II';
			repobjContact.CC_SSN__c = '888888888';
            repobjContact.CC_Contact_Type__c=System.Label.CC_RT_Representative;
            repobjContact.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Representative);
			repobjContact.CC_Physical_Address_State__c = 'Other';
			repobjContact.CC_Mailing_Address_State__c = 'Other';
			repobjContact.CC_Contact_County__c = 'Other';
			repobjContact.CC_Mailing_Address_County__c = 'Other';
			insert repobjContact;
            
            Contact legobjContact = new Contact();
			legobjContact.Birthdate =  Date.newInstance(1999, 10 , 21);
			legobjContact.FirstName = 'TestFirstName1'.toUpperCase();
			legobjContact.LastName = 'TestLastName1'.toUpperCase();
			legobjContact.CC_Gender__c = 'Male';
            legobjContact.CC_Contact_Type__c=System.Label.CC_RT_Legal_Guardian;
            legobjContact.CC_Suffix__c = 'II';
			legobjContact.CC_SSN__c = '888888888';
			legobjContact.RecordTypeId = CC_Utility.getRecordTypeId(CC_Constants.CC_CONTACT_OBJ, System.label.CC_RT_Representative);
			legobjContact.CC_Physical_Address_State__c = 'Other';
			legobjContact.CC_Mailing_Address_State__c = 'Other';
			legobjContact.CC_Contact_County__c = 'Other';
			legobjContact.CC_Mailing_Address_County__c = 'Other';
			insert legobjContact;
            
            CC_Application__c objApp = new CC_Application__c();
			objApp.CC_Does_Individual_have_Auth_Rep__c = true;
			objApp.CC_individual_have_LegalGuardian__c = true;
			objApp.CC_Individual_Also_Your_Legal_Guardian__c=false;
			objApp.CC_You_Your_Guardian_LiveAt_Same_Place__c=false;
            objApp.CC_You_Your_Rep_LiveAt_Same_Place__c=false;
            objApp.CC_Individual__c=objContact.Id;
			insert objApp;
            
            String srepobjContact = JSON.serialize(repobjContact);
            String slegobjContact = JSON.serialize(legobjContact);
            String sobjApp = JSON.serialize(objApp);
            
            Test.startTest();
            
          
        System.runAs(userAppintake){
	            map<String,String> mapLabels = CC_Representative_InformationController.loadLabels();
				String strLoadData = CC_Representative_InformationController.loadContactData(objApp.id);
				String saveResult=CC_Representative_InformationController.doSave(srepobjContact,slegobjContact,sobjApp);
            }		
			System.runAs(userCaseManager){
	            map<String,String> mapLabels = CC_Representative_InformationController.loadLabels();
				String strLoadData = CC_Representative_InformationController.loadContactData(objApp.id);
				String saveResult=CC_Representative_InformationController.doSave(srepobjContact,slegobjContact,sobjApp);
            }
            Test.stopTest();
            
    } 
    
}